/**
 * Every string the admin panel shows, in English and Arabic.
 *
 * Parity is a compile error, not a convention. `EN` is the source of truth,
 * `AdminStrings` is its type, and `AR` is annotated with it — so a key missing
 * from the Arabic bundle fails `tsc`, an extra one is an excess-property error,
 * and nested objects are checked structurally. Inside the maps keyed by an
 * engine id, `satisfies Record<Id, string>` enforces coverage of the id union
 * while keeping the literal keys in the type: add a `WarningId` in
 * pricing/types.ts and BOTH bundles stop compiling until they name it.
 *
 * This is deliberately not the customer bundle. Those strings are reassurance
 * ("our engineer will review this with you") and the admin needs the terse
 * version of the same fact. Where the two overlap — the labels for stored
 * form values — the admin reuses the customer maps instead (see i18n.tsx).
 *
 * Pure data, no React: vitest imports it in Node to walk both trees.
 */
import type { Lang } from '../i18n'
import type { CommercialFlag } from '../pricing/types'
import type { ReferenceCaseId } from '../pricing/referenceCases'
import type { AssumptionId, ConstraintId, EngineResult, SizingMethod, WarningId } from '../pricing/types'
import type { PluralForms } from './format'

export type TabId = 'submissions' | 'pricing' | 'sizing'

type Tier = EngineResult['recommendedTier']
type Confidence = EngineResult['confidence']

/**
 * Identity with a type: it widens the property to `PluralForms` so the Arabic
 * bundle can supply all six CLDR forms where English supplies two.
 */
const plural = (p: PluralForms): PluralForms => p

const EN = {
  common: {
    yes: 'Yes',
    no: 'No',
    dash: '—',
    loading: 'Loading…',
    cancel: 'Cancel',
    delete: 'Delete',
    add: 'Add',
    activate: 'Activate',
    active: 'Active',
    copy: 'Copy summary',
    copied: 'Copied',
    /** Currency word that follows a figure. */
    currency: 'LYD',
    langName: { ar: 'Arabic', en: 'English' } satisfies Record<Lang, string>,
    /** The glyph on the language toggle for each language. */
    langShort: { ar: 'ع', en: 'EN' } satisfies Record<Lang, string>,
    switchTo: { ar: 'Switch to Arabic', en: 'Switch to English' } satisfies Record<Lang, string>,
  },

  app: {
    title: 'Al Qema — Admin',
    signOut: 'Sign out',
    tab: { submissions: 'Leads', pricing: 'Pricing', sizing: 'Sizing' } satisfies Record<TabId, string>,
    tablistLabel: 'Admin sections',
    demoBanner:
      'DEMO MODE — sample data only. These are not real customers, and nothing you change here is saved.',
  },

  login: {
    email: 'Email',
    password: 'Password',
    signIn: 'Sign in',
  },

  leads: {
    count: plural({ one: '{n} submission', other: '{n} submissions' }),
    exportCsv: 'Export CSV',
    showMore: (n: string, remaining: string) => `Show ${n} more (${remaining} remaining)`,
    emptyTitle: 'No submissions yet',
    emptyBody: 'Leads appear here the moment a customer finishes the wizard.',
    loadingList: 'Loading submissions…',
    cols: {
      when: 'When',
      name: 'Name',
      whatsapp: 'WhatsApp',
      city: 'City',
      property: 'Property',
      lang: 'Language',
      tier: 'Tier',
      price: 'Price',
      confidence: 'Confidence',
    },
    siteVisitNoPrice: 'Site visit — no price',
    customPill: 'custom',
    lowConfidencePill: 'low confidence',
    demoPill: 'DEMO DATA',
    openLead: (name: string) => 'Open lead ' + name,
    closeLead: 'Close lead',
    ref: 'ref',
    whatsapp: 'WhatsApp',
  },

  detail: {
    recommendedSystem: 'Recommended system',
    inverter: 'Inverter',
    panels: 'Panels',
    battery: 'Battery',
    nightRuntime: 'Night runtime',
    noNightLoad: 'no night load',
    usable: 'usable',
    yearsShort: 'yr',
    chemistry: { liquid: 'liquid', lithium: 'lithium' } satisfies Record<'liquid' | 'lithium', string>,
    surveyTitle: 'Could not be calculated',
    surveyBody:
      'No system was sized and no price was quoted — the answers produced figures that could not be calculated. Size is never the reason; check the form values.',
    sizingMethod: 'Sizing method',
    method: {
      packages: 'Standard package',
      residentialBom: 'Custom build — household components',
      commercial: 'Commercial method',
    } satisfies Record<SizingMethod, string>,
    engineeringNotes: 'Engineering notes',
    lowConfidenceTitle: 'Low confidence — check before quoting',
    notesTitle: 'Notes',
    assumed: 'Assumed',
    sizedBy: 'Sized by',
    customer: 'Customer',
    phone: 'Phone',
    city: 'City',
    property: 'Property',
    otherPrefix: 'Other — ',
    unspecified: 'unspecified',
    language: 'Language',
    answers: 'Answers',
    dailyCuts: 'Daily cuts',
    keepRunning: 'Keep running',
    nightEconomy: 'Night economy',
    acUnits: 'AC units',
    ac: (n: string) => 'AC ' + n,
    unknownSize: 'unknown size',
    nights: 'nights',
    inverterAc: 'inverter',
    fridge: 'Fridge',
    freezer: 'Freezer',
    alwaysOn: 'always on',
    lighting: 'Lighting',
    bulbs: plural({ one: '{n} bulb', other: '{n} bulbs' }),
    customDevice: 'Custom device',
    systemType: 'System type',
    cutPriority: 'Cut priority',
    roof: 'Roof',
    shade: 'shade',
    customerNotes: 'Customer notes',
    loadAudit: 'Load audit',
    perDay: 'kWh/day',
    nightKwh: 'kWh night',
    peakKw: 'kW peak',
    loadCols: {
      load: 'Load',
      avgW: 'Avg W',
      peakW: 'Peak W',
      qty: 'Qty',
      hoursPerDay: 'h/day',
      night: 'Night',
      assumed: 'Assumed',
    },
    hoursPerDay: 'h/day',
    nightPill: 'night',
    assumedPill: 'assumed',
    customBuild: 'Custom build (internal)',
    bomCols: { component: 'Component', qty: 'Qty', unit: 'Unit', total: 'Total' },
    partsSubtotal: 'Parts subtotal',
    quoted: 'Quoted',
    floorApplied: 'floor applied',
  },

  labels: {
    warning: {
      heavyDutyLoad: 'Heavy appliance in the load list',
      acBtuExceeded: 'An AC exceeds this tier’s BTU cap',
      customFloorApplied: 'Priced at the custom-build floor, not the parts total',
      roofSpaceTight: 'Array may not fit the roof the customer described',
    } satisfies Record<WarningId, string>,
    assumption: {
      acSizeAssumed: 'AC size (customer did not know)',
      lightingAssumed: 'Bulb wattage',
      customApplianceAssumed: 'Power of a custom device',
      usageHoursAssumed: 'Daily running hours',
    } satisfies Record<AssumptionId, string>,
    constraint: {
      inverter: 'inverter power',
      battery: 'battery storage',
      panels: 'panel count',
      acCount: 'number of ACs',
      acBtu: 'AC size (BTU)',
    } satisfies Record<ConstraintId, string>,
    flag: {
      residentialScale:
        'This is a household-sized load. The smallest stocked inverter is far bigger than it needs — quote it from the packages instead.',
      aboveLargestInverter:
        'The peak load is above the largest stocked inverter, so the size shown is capped. This job needs multiple units and an engineer.',
      dcAcRatioHigh:
        'The array is much larger than the inverter the method selects. The method sizes the inverter from the daytime load alone, but the array also has to recharge the battery bank — confirm whether the inverter carries the charging, or whether separate charge controllers do.',
    } satisfies Record<CommercialFlag, string>,
    tier: {
      S: 'S',
      M: 'M',
      L: 'L',
      XL: 'XL',
      XXL: 'XXL',
      CUSTOM: 'Custom',
      SURVEY: 'Survey',
    } satisfies Record<Tier, string>,
    confidence: { high: 'high', low: 'low' } satisfies Record<Confidence, string>,
    /** Short property labels so the card meta line stays on one line at 390px. */
    propertyShort: {
      Home: 'Home',
      'Office / Company': 'Office',
      Shop: 'Shop',
      Clinic: 'Clinic',
      Workshop: 'Workshop',
      Other: 'Other',
    } as Record<string, string>,
  },

  csv: {
    date: 'Date',
    name: 'Name',
    whatsapp: 'WhatsApp',
    city: 'City',
    property: 'Property',
    language: 'Language',
    tier: 'Tier',
    priceLyd: 'Price (LYD)',
    custom: 'Custom',
    confidence: 'Confidence',
    pricingRef: 'Pricing ref',
  },

  pricing: {
    loading: 'Loading pricing config…',
    cannotSave: 'Cannot save — fix the following first:',
    problemsSeeTop: plural({
      one: '{n} problem — see top of page',
      other: '{n} problems — see top of page',
    }),
    savedNotice: (v: string) => `Saved and activated ${v} — live for new visitors immediately.`,
    activatedNotice: (v: string) => `Activated ${v}.`,
    insertFailed: 'insert failed',
    packages: 'Packages',
    cols: {
      tier: 'Tier',
      price: 'Price (LYD)',
      inverterKva: 'Inverter kVA',
      panels: 'Panels',
      panelW: 'Panel W',
      battery: 'Battery',
      maxAcs: 'Max ACs',
      maxAcBtu: 'Max AC BTU',
    },
    unitAhLiquid: 'Ah liquid',
    unitKwhLithium: 'kWh lithium',
    customBom: 'Custom-system pricing (BOM)',
    minimumPrice: 'Minimum price / floor (LYD)',
    roundUpTo: 'Round up to (LYD)',
    panel: 'Panel',
    battery: 'Battery',
    singleInverter: 'Single inverter (≤ kW)',
    parallelInverter: 'Parallel inverter (kW each)',
    panelsPerStand: 'Panels per stand',
    componentList: 'Component price list (LYD)',
    removeComponent: (name: string) => 'Remove ' + name,
    newComponentPlaceholder: 'New component name',
    applianceAssumptions: 'Appliance assumptions (watts / hours per day)',
    alwaysOnSuffix: '(always on)',
    sizingConstants: 'Sizing constants',
    fields: {
      acWattsStandard: 'AC W per BTU (standard)',
      acWattsInverter: 'AC W per BTU (inverter)',
      assumedAcBtu: 'Assumed AC BTU (unknown)',
      lightingHours: 'Lighting hours/day',
      fridgeWDuty: 'Fridge W / duty',
      freezerWDuty: 'Freezer W / duty',
      peakSunHours: 'Peak sun hours',
      systemEfficiency: 'System efficiency (0–1)',
      inverterSafetyFactor: 'Inverter safety factor',
      diversityFactor: 'Diversity factor (0–1)',
      liquidBatteryV: 'Liquid battery V',
      dod: 'DoD liquid / lithium (0–1)',
      addOnBatteryBox: 'Add-on: battery box (LYD)',
      takesOverAboveKw: 'Commercial method above (kW)',
    },
    versionHistory: 'Version history',
    unsaved: 'Unsaved changes',
    noChanges: 'No changes',
    saving: 'Saving…',
    saveActivate: 'Save & activate',
    saveActivateAs: 'Save & activate as',
    /** The six households re-priced before every publish. */
    referenceCase: {
      smallFlat: 'Small flat',
      familyHomeOneAc: 'Family home, one AC',
      homeAcAndFreezer: 'Home, AC and freezer',
      homeTwoAcs: 'Home with two ACs',
      shop: 'Shop',
      largeVilla: 'Large villa',
      workshop: 'Workshop',
    } satisfies Record<ReferenceCaseId, string>,
    /**
     * Human labels for config paths and validator reasons. The validator
     * speaks in `packages[2].priceLyd: must be a positive number`; a manager
     * reads "Packages · L package · price (LYD) — must be a number above 0".
     */
    paths: {
      section: {
        configVersion: 'Version',
        currency: 'Currency',
        acBtuCapMode: 'Oversized-AC behaviour',
        packages: 'Packages',
        includes: 'Included items',
        addOns: 'Add-ons',
        batteryLifespanYears: 'Battery lifespan (years)',
        components: 'Component prices',
        loadDefaults: 'Appliance assumptions',
        sizing: 'Household sizing',
        customBom: 'Custom build',
        commercial: 'Large-system method',
      } as Record<string, string>,
      field: {
        tier: 'tier',
        inverterKva: 'inverter (kVA)',
        panel: 'panels',
        count: 'count',
        watts: 'watts (W)',
        battery: 'battery',
        chemistry: 'battery type',
        ampHours: 'capacity (Ah)',
        kwhEach: 'capacity each (kWh)',
        maxAcUnits: 'max ACs',
        maxAcBtu: 'max AC size (BTU)',
        priceLyd: 'price (LYD)',
        name: 'name',
        liquid: 'liquid',
        lithium: 'lithium',
        acWattsPerBtu: 'AC watts per BTU',
        standard: 'standard',
        inverter: 'inverter',
        assumedAcBtu: 'assumed AC size when unknown (BTU)',
        btuPerTon: 'BTU per ton',
        lightingWattsByType: 'bulb wattage by type (W)',
        led: 'LED',
        regular: 'regular',
        mixed: 'mixed',
        lightingHours: 'lighting hours per day',
        fridge: 'fridge',
        freezer: 'freezer',
        duty: 'duty cycle',
        fridgeConditionMultiplier: 'fridge condition multiplier',
        new: 'new',
        old: 'old',
        defaultFridgeCondition: 'default fridge condition',
        appliancesByName: 'appliances',
        hours: 'hours per day',
        night: 'runs at night',
        alwaysOn: 'always on',
        customAppliance: '“other device” default',
        peakSunHours: 'peak sun hours (h)',
        systemEfficiency: 'system efficiency',
        inverterSafetyFactor: 'inverter safety factor',
        diversityFactor: 'diversity factor',
        liquidBatteryVoltageV: 'liquid battery voltage (V)',
        kvaToKw: 'power factor (kW per kVA)',
        alwaysOnNightHours: 'night hours (h)',
        dodByChemistry: 'depth of discharge',
        surgeFactorByCategory: 'surge factors',
        ac: 'AC',
        cold: 'fridges & freezers',
        lighting: 'lighting',
        appliance: 'other appliances',
        panelAreaM2: 'area per panel (m²)',
        roofAreaM2ByAnswer: 'roof area by answer (m²)',
        single: 'single inverter',
        parallel: 'parallel inverter',
        maxKw: 'max (kW)',
        unitKw: 'each (kW)',
        component: 'part',
        stand: 'stand',
        panelsPerStand: 'panels per stand',
        perPanel: 'per-panel items',
        perInverter: 'per-inverter items',
        fixed: 'one-off items',
        qty: 'quantity',
        roundUpToLyd: 'round up to (LYD)',
        minimumLyd: 'minimum price (LYD)',
        batteryEfficiency: 'battery efficiency',
        inverterLadder: 'inverter sizes',
        kw: 'size (kW)',
        maxDcAcRatio: 'max DC:AC ratio',
        customerPath: 'customer quotes',
        takesOverAboveKw: 'commercial method above (kW)',
      } as Record<string, string>,
      packageItem: (tier: string) => `${tier} package`,
      listItem: (n: number) => `item ${n}`,
      ladderItem: (n: number) => `size ${n}`,
      reason: {
        positive: 'must be a number above 0',
        nonNegative: 'must be 0 or more',
        wholeNumber: 'must be a whole number, 0 or more',
        between: (min: string, max: string) => `must be between ${min} and ${max}`,
        fraction: 'must be above 0 and at most 1',
        positiveOrEmpty: 'must be empty or a number above 0',
        monotonic: 'package prices must not go down from S to XXL',
        floorBelowXxl: (n: string) => `must be at least the XXL price (${n}), or custom builds would undercut it`,
        unknownComponent: 'names a part that is not in the component price list',
        missingPreset: (name: string) => `the form offers “${name}”, so it needs a power figure`,
        ascending: 'sizes must go from small to large',
        atLeastOne: 'needs at least one entry',
        needsName: 'needs a part name',
        emptyName: 'one component has an empty name',
        addOn: 'every add-on needs a name and a price above 0',
        chemistry: 'must be liquid or lithium',
        acBtuCapMode: 'must be “warn but still offer the package” or “move the customer up a package”',
        newOrOld: 'must be new or old',
        liquidBattery: 'a liquid battery needs a whole-number count above 0 and Ah above 0',
        lithiumBattery: 'a lithium battery needs a whole-number count above 0 and kWh above 0',
        panelSpec: 'needs a whole-number panel count above 0 and watts above 0',
        wattsDuty: 'needs watts above 0 and a duty cycle above 0 and at most 1',
        wattsHours: 'needs watts above 0 and hours 0 or more',
        watts: 'needs watts above 0',
        hours24: 'must be between 0 and 24 hours',
        pairPositive: 'both values must be above 0',
        allPositive: 'every value must be above 0',
        dodPair: 'liquid and lithium must each be above 0 and at most 1',
        lifespanPair: 'liquid and lithium must both be above 0',
        surge: 'each surge factor must be between 1 and 10',
        panelArea: 'must be above 0 and under 20 m²',
        roofAreas: 'every roof area must be 0 m² or more',
        componentAndWatts: 'needs a part from the price list and watts above 0',
        componentAndKwh: 'needs a part from the price list and kWh above 0',
        inverterParts: 'both inverters need a part from the price list and a kW rating above 0',
        standParts: 'needs a part from the price list and a whole number of panels per stand above 0',
        qty: 'needs a quantity above 0',
        kwAndName: 'needs a size in kW above 0 and a part name',
        ratio: 'must be at least 1',
        structural: 'this part of the config is not in the expected shape — reload the page before editing',
      },
    },
  },

  sizing: {
    banner:
      'Internal estimate — not a customer quote. Sized with Al Qema’s commercial method; prices are indicative and every figure needs an engineer’s sign-off.',
    job: 'The job',
    batteryKwh: 'Daily battery energy (kWh)',
    dayLoadKw: 'Daytime load (kW)',
    peakKw: 'Peak load (kW)',
    help: 'Battery energy is what has to come out of the bank overnight. Daytime load is what the panels carry directly. Peak defaults to the daytime load.',
    usingPeak: 'Using',
    checkNumbers: 'Check the numbers',
    system: 'System',
    batteries: 'batteries',
    arrayCaption: 'array',
    inverter: 'inverter',
    steps: {
      gross: 'gross energy, then batteries',
      recharge: 'to recharge the bank',
      array: 'array, then panels',
      inverter: 'inverter from the peak load',
    },
    loadPlusCharging: 'load + charging would be',
    checkBeforeQuoting: 'Check before quoting',
    partsList: 'Indicative parts list',
    cols: { item: 'Item', qty: 'Qty', unit: 'Unit', total: 'Total' },
    noPrice: 'no price',
    pricedRounded: 'Priced items, rounded up',
    unpricedNote: plural({
      one: '{n} item is not in the price list, so the total above is incomplete:',
      other: '{n} items are not in the price list, so the total above is incomplete:',
    }),
    unpricedHint: 'Add them in Pricing → Component price list and this fills in.',
    method: 'Method',
    methodParts: {
      batteryEff: 'battery efficiency',
      systemEff: 'system efficiency',
      sunHours: 'peak sun hours',
      panels: 'W panels',
      batteries: 'kWh batteries',
    },
    builtInFigures:
      'These are the built-in figures — publish the pricing config once to make them editable.',
    builtInPrices: 'Component prices are the built-in list.',
    customerLive: 'Customer quotes: systems above',
    customerLiveTail: 'of inverter demand are priced by this method automatically.',
    customerWaiting: 'Customer quotes will switch to this method for systems above',
    customerWaitingTail: 'as soon as these are priced in the component list:',
    customerMeanwhile: 'Until then large systems are priced from the household component list — still automatically, still with a number.',
    summary: {
      title: 'Indicative sizing — not a customer quote',
      batteries: 'Batteries',
      panels: 'Panels',
      inverter: 'Inverter',
      gross: 'gross',
      array: 'array',
      partsTotal: 'Indicative parts total',
      stillUnpriced: plural({
        one: '{n} item still unpriced',
        other: '{n} items still unpriced',
      }),
    },
  },
}

export type AdminStrings = typeof EN

export const AR: AdminStrings = {
  common: {
    yes: 'نعم',
    no: 'لا',
    dash: '—',
    loading: 'جارٍ التحميل…',
    cancel: 'إلغاء',
    delete: 'حذف',
    add: 'إضافة',
    activate: 'تفعيل',
    active: 'مفعّل',
    copy: 'نسخ الملخص',
    copied: 'تم النسخ',
    currency: 'د.ل',
    langName: { ar: 'العربية', en: 'الإنجليزية' },
    langShort: { ar: 'ع', en: 'EN' },
    switchTo: { ar: 'التبديل إلى العربية', en: 'التبديل إلى الإنجليزية' },
  },

  app: {
    title: 'القمة — لوحة الإدارة',
    signOut: 'تسجيل الخروج',
    tab: { submissions: 'الطلبات', pricing: 'الأسعار', sizing: 'التحجيم' },
    tablistLabel: 'أقسام لوحة الإدارة',
    demoBanner:
      'وضع العرض التجريبي — بيانات تجريبية فقط. هؤلاء ليسوا عملاء حقيقيين، ولا يُحفظ أي تغيير هنا.',
  },

  login: {
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    signIn: 'تسجيل الدخول',
  },

  leads: {
    count: {
      zero: 'لا طلبات',
      one: 'طلب واحد',
      two: 'طلبان',
      few: '{n} طلبات',
      many: '{n} طلبًا',
      other: '{n} طلب',
    },
    exportCsv: 'تصدير CSV',
    showMore: (n, remaining) => `عرض ${n} أخرى (${remaining} متبقية)`,
    emptyTitle: 'لا توجد طلبات بعد',
    emptyBody: 'تظهر الطلبات هنا فور إكمال العميل للنموذج.',
    loadingList: 'جارٍ تحميل الطلبات…',
    cols: {
      when: 'الوقت',
      name: 'الاسم',
      whatsapp: 'واتساب',
      city: 'المدينة',
      property: 'نوع المكان',
      lang: 'اللغة',
      tier: 'الباقة',
      price: 'السعر',
      confidence: 'الثقة',
    },
    siteVisitNoPrice: 'معاينة الموقع — بدون سعر',
    customPill: 'مخصّص',
    lowConfidencePill: 'ثقة منخفضة',
    demoPill: 'بيانات تجريبية',
    openLead: (name) => 'فتح الطلب ' + name,
    closeLead: 'إغلاق الطلب',
    ref: 'مرجع',
    whatsapp: 'واتساب',
  },

  detail: {
    recommendedSystem: 'النظام المقترح',
    inverter: 'الإنفرتر',
    panels: 'الألواح',
    battery: 'البطارية',
    nightRuntime: 'مدة التشغيل الليلي',
    noNightLoad: 'لا حمل ليلي',
    usable: 'قابل للاستخدام',
    yearsShort: 'سنة',
    chemistry: { liquid: 'سائلة', lithium: 'ليثيوم' },
    surveyTitle: 'لم يمكن حسابه',
    surveyBody:
      'لم يُحدَّد نظام ولم يُعرض سعر — أنتجت الإجابات أرقامًا لا يمكن حسابها. الحجم ليس السبب أبدًا؛ راجع قيم النموذج.',
    sizingMethod: 'طريقة التحجيم',
    method: {
      packages: 'باقة قياسية',
      residentialBom: 'تركيبة مخصّصة — مكوّنات منزلية',
      commercial: 'الطريقة التجارية',
    },
    engineeringNotes: 'ملاحظات هندسية',
    lowConfidenceTitle: 'ثقة منخفضة — راجع قبل التسعير',
    notesTitle: 'ملاحظات',
    assumed: 'مُفترَض',
    sizedBy: 'حُدِّد الحجم حسب',
    customer: 'العميل',
    phone: 'الهاتف',
    city: 'المدينة',
    property: 'نوع المكان',
    otherPrefix: 'أخرى — ',
    unspecified: 'غير محدد',
    language: 'اللغة',
    answers: 'الإجابات',
    dailyCuts: 'ساعات الانقطاع',
    keepRunning: 'ما يجب تشغيله',
    nightEconomy: 'الاقتصاد الليلي',
    acUnits: 'عدد المكيفات',
    ac: (n) => 'مكيف ' + n,
    unknownSize: 'قدرة غير معروفة',
    nights: 'ليلًا',
    inverterAc: 'إنفرتر',
    fridge: 'الثلاجة',
    freezer: 'الفريزر',
    alwaysOn: 'يعمل دائمًا',
    lighting: 'الإنارة',
    bulbs: {
      zero: 'لا مصابيح',
      one: 'مصباح واحد',
      two: 'مصباحان',
      few: '{n} مصابيح',
      many: '{n} مصباحًا',
      other: '{n} مصباح',
    },
    customDevice: 'جهاز مخصّص',
    systemType: 'نوع النظام',
    cutPriority: 'الأولوية عند الانقطاع',
    roof: 'السطح',
    shade: 'الظل',
    customerNotes: 'ملاحظات العميل',
    loadAudit: 'تفصيل الأحمال',
    perDay: 'ك.و.س/يوم',
    nightKwh: 'ك.و.س ليلًا',
    peakKw: 'ك.و ذروة',
    loadCols: {
      load: 'الحمل',
      avgW: 'واط متوسط',
      peakW: 'واط ذروة',
      qty: 'العدد',
      hoursPerDay: 'س/يوم',
      night: 'ليلي',
      assumed: 'مُفترَض',
    },
    hoursPerDay: 'س/يوم',
    nightPill: 'ليلي',
    assumedPill: 'مُفترَض',
    customBuild: 'التركيبة المخصّصة (داخلي)',
    bomCols: { component: 'المكوّن', qty: 'العدد', unit: 'سعر الوحدة', total: 'الإجمالي' },
    partsSubtotal: 'مجموع القطع',
    quoted: 'السعر المعروض',
    floorApplied: 'طُبِّق الحد الأدنى',
  },

  labels: {
    warning: {
      heavyDutyLoad: 'جهاز ثقيل في قائمة الأحمال',
      acBtuExceeded: 'مكيف يتجاوز حد BTU لهذه الباقة',
      customFloorApplied: 'سُعِّر بالحد الأدنى للتركيبة المخصّصة، لا بمجموع القطع',
      roofSpaceTight: 'قد لا تتسع الألواح على السطح الذي وصفه العميل',
    },
    assumption: {
      acSizeAssumed: 'قدرة المكيف (العميل لا يعرفها)',
      lightingAssumed: 'قدرة المصابيح',
      customApplianceAssumed: 'قدرة جهاز مخصّص',
      usageHoursAssumed: 'ساعات التشغيل اليومية',
    },
    constraint: {
      inverter: 'قدرة الإنفرتر',
      battery: 'سعة البطاريات',
      panels: 'عدد الألواح',
      acCount: 'عدد المكيفات',
      acBtu: 'قدرة المكيف (BTU)',
    },
    flag: {
      residentialScale:
        'هذا حمل بحجم منزلي. أصغر إنفرتر متوفر أكبر بكثير مما يلزم — سعِّره من الباقات بدلًا من ذلك.',
      aboveLargestInverter:
        'حمل الذروة أعلى من أكبر إنفرتر متوفر، لذا القدرة المعروضة محدودة بالحد الأقصى. يحتاج هذا المشروع إلى عدة وحدات وإلى مهندس.',
      dcAcRatioHigh:
        'الألواح أكبر بكثير من الإنفرتر الذي تختاره الطريقة. الطريقة تحدد الإنفرتر من حمل النهار فقط، بينما يجب أن تشحن الألواح البطاريات أيضًا — تأكد هل الإنفرتر يتحمل الشحن، أم تتولاه منظمات شحن منفصلة.',
    },
    tier: {
      S: 'S',
      M: 'M',
      L: 'L',
      XL: 'XL',
      XXL: 'XXL',
      CUSTOM: 'مخصّص',
      SURVEY: 'معاينة',
    },
    confidence: { high: 'عالية', low: 'منخفضة' },
    propertyShort: {
      Home: 'منزل',
      'Office / Company': 'مكتب',
      Shop: 'محل',
      Clinic: 'عيادة',
      Workshop: 'ورشة',
      Other: 'أخرى',
    },
  },

  csv: {
    date: 'التاريخ',
    name: 'الاسم',
    whatsapp: 'واتساب',
    city: 'المدينة',
    property: 'نوع المكان',
    language: 'اللغة',
    tier: 'الباقة',
    priceLyd: 'السعر (د.ل)',
    custom: 'مخصّص',
    confidence: 'الثقة',
    pricingRef: 'مرجع التسعير',
  },

  pricing: {
    loading: 'جارٍ تحميل إعدادات الأسعار…',
    cannotSave: 'لا يمكن الحفظ — عالج ما يلي أولًا:',
    problemsSeeTop: {
      one: 'مشكلة واحدة — انظر أعلى الصفحة',
      two: 'مشكلتان — انظر أعلى الصفحة',
      few: '{n} مشاكل — انظر أعلى الصفحة',
      many: '{n} مشكلة — انظر أعلى الصفحة',
      other: '{n} مشكلة — انظر أعلى الصفحة',
    },
    savedNotice: (v) => `تم الحفظ والتفعيل ${v} — يسري على الزوار الجدد فورًا.`,
    activatedNotice: (v) => `تم تفعيل ${v}.`,
    insertFailed: 'فشل الإدخال',
    packages: 'الباقات',
    cols: {
      tier: 'الباقة',
      price: 'السعر (د.ل)',
      inverterKva: 'الإنفرتر kVA',
      panels: 'الألواح',
      panelW: 'واط/لوح',
      battery: 'البطارية',
      maxAcs: 'أقصى عدد مكيفات',
      maxAcBtu: 'أقصى BTU للمكيف',
    },
    unitAhLiquid: 'Ah سائلة',
    unitKwhLithium: 'kWh ليثيوم',
    customBom: 'تسعير النظام المخصّص (قائمة المكوّنات)',
    minimumPrice: 'الحد الأدنى للسعر (د.ل)',
    roundUpTo: 'التقريب لأعلى إلى (د.ل)',
    panel: 'اللوح',
    battery: 'البطارية',
    singleInverter: 'إنفرتر مفرد (≤ kW)',
    parallelInverter: 'إنفرتر متوازٍ (kW للوحدة)',
    panelsPerStand: 'ألواح لكل قاعدة',
    componentList: 'قائمة أسعار المكوّنات (د.ل)',
    removeComponent: (name) => 'حذف ' + name,
    newComponentPlaceholder: 'اسم مكوّن جديد',
    applianceAssumptions: 'افتراضات الأجهزة (واط / ساعات في اليوم)',
    alwaysOnSuffix: '(يعمل دائمًا)',
    sizingConstants: 'ثوابت التحجيم',
    fields: {
      acWattsStandard: 'واط لكل BTU للمكيف (عادي)',
      acWattsInverter: 'واط لكل BTU للمكيف (إنفرتر)',
      assumedAcBtu: 'BTU المفترض للمكيف (غير معروف)',
      lightingHours: 'ساعات الإنارة/يوم',
      fridgeWDuty: 'الثلاجة واط / نسبة التشغيل',
      freezerWDuty: 'الفريزر واط / نسبة التشغيل',
      peakSunHours: 'ساعات الشمس الفعّالة',
      systemEfficiency: 'كفاءة النظام (0–1)',
      inverterSafetyFactor: 'معامل أمان الإنفرتر',
      diversityFactor: 'معامل التنوّع (0–1)',
      liquidBatteryV: 'جهد البطارية السائلة (V)',
      dod: 'عمق التفريغ سائلة / ليثيوم (0–1)',
      addOnBatteryBox: 'إضافة: صندوق البطاريات (د.ل)',
      takesOverAboveKw: 'الطريقة التجارية فوق (kW)',
    },
    versionHistory: 'سجل الإصدارات',
    unsaved: 'تغييرات غير محفوظة',
    noChanges: 'لا تغييرات',
    saving: 'جارٍ الحفظ…',
    saveActivate: 'حفظ وتفعيل',
    saveActivateAs: 'حفظ وتفعيل باسم',
    referenceCase: {
      smallFlat: 'شقة صغيرة',
      familyHomeOneAc: 'منزل عائلي بمكيف واحد',
      homeAcAndFreezer: 'منزل بمكيف وفريزر',
      homeTwoAcs: 'منزل بمكيفين',
      shop: 'محل',
      largeVilla: 'فيلا كبيرة',
      workshop: 'ورشة',
    },
    paths: {
      section: {
        configVersion: 'الإصدار',
        currency: 'العملة',
        acBtuCapMode: 'سلوك المكيف الأكبر من الباقة',
        packages: 'الباقات',
        includes: 'العناصر المشمولة',
        addOns: 'الإضافات',
        batteryLifespanYears: 'عمر البطارية (سنوات)',
        components: 'أسعار المكوّنات',
        loadDefaults: 'افتراضات الأجهزة',
        sizing: 'تحجيم المنازل',
        customBom: 'النظام المخصّص',
        commercial: 'طريقة الأنظمة الكبيرة',
      },
      field: {
        tier: 'الباقة',
        inverterKva: 'الإنفرتر (kVA)',
        panel: 'الألواح',
        count: 'العدد',
        watts: 'الواط (W)',
        battery: 'البطارية',
        chemistry: 'نوع البطارية',
        ampHours: 'السعة (Ah)',
        kwhEach: 'سعة الوحدة (kWh)',
        maxAcUnits: 'أقصى عدد مكيفات',
        maxAcBtu: 'أقصى حجم مكيف (BTU)',
        priceLyd: 'السعر (د.ل)',
        name: 'الاسم',
        liquid: 'سائلة',
        lithium: 'ليثيوم',
        acWattsPerBtu: 'واط المكيف لكل BTU',
        standard: 'عادي',
        inverter: 'إنفرتر',
        assumedAcBtu: 'حجم المكيف المفترض عند عدم المعرفة (BTU)',
        btuPerTon: 'BTU لكل طن',
        lightingWattsByType: 'واط المصباح حسب النوع (W)',
        led: 'LED',
        regular: 'عادي',
        mixed: 'مختلط',
        lightingHours: 'ساعات الإنارة في اليوم',
        fridge: 'الثلاجة',
        freezer: 'الفريزر',
        duty: 'نسبة التشغيل',
        fridgeConditionMultiplier: 'معامل حالة الثلاجة',
        new: 'جديدة',
        old: 'قديمة',
        defaultFridgeCondition: 'حالة الثلاجة الافتراضية',
        appliancesByName: 'الأجهزة',
        hours: 'ساعات في اليوم',
        night: 'يعمل ليلًا',
        alwaysOn: 'يعمل دائمًا',
        customAppliance: 'افتراض «جهاز آخر»',
        peakSunHours: 'ساعات الشمس الفعّالة (h)',
        systemEfficiency: 'كفاءة النظام',
        inverterSafetyFactor: 'معامل أمان الإنفرتر',
        diversityFactor: 'معامل التنوّع',
        liquidBatteryVoltageV: 'جهد البطارية السائلة (V)',
        kvaToKw: 'معامل القدرة (kW لكل kVA)',
        alwaysOnNightHours: 'ساعات الليل (h)',
        dodByChemistry: 'عمق التفريغ',
        surgeFactorByCategory: 'معاملات الذروة',
        ac: 'المكيفات',
        cold: 'الثلاجات والفريزرات',
        lighting: 'الإنارة',
        appliance: 'الأجهزة الأخرى',
        panelAreaM2: 'مساحة اللوح (م²)',
        roofAreaM2ByAnswer: 'مساحة السطح حسب الإجابة (م²)',
        single: 'إنفرتر مفرد',
        parallel: 'إنفرتر متوازٍ',
        maxKw: 'الأقصى (kW)',
        unitKw: 'للوحدة (kW)',
        component: 'القطعة',
        stand: 'القاعدة',
        panelsPerStand: 'ألواح لكل قاعدة',
        perPanel: 'بنود لكل لوح',
        perInverter: 'بنود لكل إنفرتر',
        fixed: 'بنود ثابتة',
        qty: 'الكمية',
        roundUpToLyd: 'التقريب لأعلى إلى (د.ل)',
        minimumLyd: 'الحد الأدنى للسعر (د.ل)',
        batteryEfficiency: 'كفاءة البطارية',
        inverterLadder: 'أحجام الإنفرتر',
        kw: 'الحجم (kW)',
        maxDcAcRatio: 'أقصى نسبة DC:AC',
        customerPath: 'عروض العملاء',
        takesOverAboveKw: 'الطريقة التجارية فوق (kW)',
      },
      packageItem: (tier) => `باقة ${tier}`,
      listItem: (n) => `البند ${n}`,
      ladderItem: (n) => `الحجم ${n}`,
      reason: {
        positive: 'يجب أن يكون رقمًا أكبر من 0',
        nonNegative: 'يجب أن يكون 0 أو أكثر',
        wholeNumber: 'يجب أن يكون عددًا صحيحًا، 0 أو أكثر',
        between: (min, max) => `يجب أن يكون بين ${min} و${max}`,
        fraction: 'يجب أن يكون أكبر من 0 ولا يتجاوز 1',
        positiveOrEmpty: 'يجب أن يكون فارغًا أو رقمًا أكبر من 0',
        monotonic: 'يجب ألا تنخفض أسعار الباقات من S إلى XXL',
        floorBelowXxl: (n) => `يجب ألا يقل عن سعر باقة XXL (${n})، وإلا صار النظام المخصّص أرخص منها`,
        unknownComponent: 'يشير إلى قطعة غير موجودة في قائمة أسعار المكوّنات',
        missingPreset: (name) => `النموذج يعرض «${name}»، فيلزمه رقم استهلاك`,
        ascending: 'يجب أن تتدرّج الأحجام من الأصغر إلى الأكبر',
        atLeastOne: 'يلزم بند واحد على الأقل',
        needsName: 'يلزم اسم قطعة',
        emptyName: 'أحد المكوّنات بلا اسم',
        addOn: 'كل إضافة تحتاج اسمًا وسعرًا أكبر من 0',
        chemistry: 'يجب أن تكون سائلة أو ليثيوم',
        acBtuCapMode: 'يجب أن يكون «تنبيه مع عرض الباقة» أو «نقل العميل إلى الباقة الأكبر»',
        newOrOld: 'يجب أن تكون جديدة أو قديمة',
        liquidBattery: 'البطارية السائلة تحتاج عددًا صحيحًا أكبر من 0 وسعة Ah أكبر من 0',
        lithiumBattery: 'بطارية الليثيوم تحتاج عددًا صحيحًا أكبر من 0 وسعة kWh أكبر من 0',
        panelSpec: 'يلزم عدد ألواح صحيح أكبر من 0 وواط أكبر من 0',
        wattsDuty: 'يلزم واط أكبر من 0 ونسبة تشغيل أكبر من 0 ولا تتجاوز 1',
        wattsHours: 'يلزم واط أكبر من 0 وساعات 0 أو أكثر',
        watts: 'يلزم واط أكبر من 0',
        hours24: 'يجب أن يكون بين 0 و24 ساعة',
        pairPositive: 'يجب أن تكون القيمتان أكبر من 0',
        allPositive: 'يجب أن تكون كل قيمة أكبر من 0',
        dodPair: 'يجب أن تكون قيمتا السائلة والليثيوم أكبر من 0 ولا تتجاوزان 1',
        lifespanPair: 'يجب أن تكون قيمتا السائلة والليثيوم أكبر من 0',
        surge: 'يجب أن يكون كل معامل ذروة بين 1 و10',
        panelArea: 'يجب أن تكون أكبر من 0 وأقل من 20 م²',
        roofAreas: 'يجب أن تكون كل مساحة سطح 0 م² أو أكثر',
        componentAndWatts: 'يلزم قطعة من قائمة الأسعار وواط أكبر من 0',
        componentAndKwh: 'يلزم قطعة من قائمة الأسعار وسعة kWh أكبر من 0',
        inverterParts: 'يحتاج الإنفرتران قطعة من قائمة الأسعار وقدرة kW أكبر من 0',
        standParts: 'يلزم قطعة من قائمة الأسعار وعدد صحيح من الألواح لكل قاعدة أكبر من 0',
        qty: 'يلزم كمية أكبر من 0',
        kwAndName: 'يلزم حجم kW أكبر من 0 واسم قطعة',
        ratio: 'يجب أن يكون 1 على الأقل',
        structural: 'هذا الجزء من الإعدادات ليس بالشكل المتوقع — أعد تحميل الصفحة قبل التعديل',
      },
    },
  },

  sizing: {
    banner:
      'تقدير داخلي — ليس عرض سعر للعميل. محسوب بطريقة القمة للمشاريع التجارية؛ الأسعار تقريبية وكل رقم يحتاج اعتماد مهندس.',
    job: 'المشروع',
    batteryKwh: 'طاقة البطاريات اليومية (kWh)',
    dayLoadKw: 'حمل النهار (kW)',
    peakKw: 'حمل الذروة (kW)',
    help: 'طاقة البطاريات هي ما يجب سحبه منها ليلًا. حمل النهار هو ما تغذّيه الألواح مباشرة. الذروة تساوي حمل النهار إن لم تُحدَّد.',
    usingPeak: 'المستخدم',
    checkNumbers: 'راجع الأرقام',
    system: 'النظام',
    batteries: 'بطاريات',
    arrayCaption: 'ألواح',
    inverter: 'إنفرتر',
    steps: {
      gross: 'الطاقة الإجمالية، ثم عدد البطاريات',
      recharge: 'لإعادة شحن البطاريات',
      array: 'قدرة الألواح، ثم عددها',
      inverter: 'الإنفرتر من حمل الذروة',
    },
    loadPlusCharging: 'الحمل + الشحن يحتاج',
    checkBeforeQuoting: 'راجع قبل التسعير',
    partsList: 'قائمة القطع التقريبية',
    cols: { item: 'القطعة', qty: 'العدد', unit: 'سعر الوحدة', total: 'الإجمالي' },
    noPrice: 'بدون سعر',
    pricedRounded: 'القطع المسعّرة، مقرّبة لأعلى',
    unpricedNote: {
      one: 'قطعة واحدة ليست في قائمة الأسعار، لذا الإجمالي أعلاه غير كامل:',
      two: 'قطعتان ليستا في قائمة الأسعار، لذا الإجمالي أعلاه غير كامل:',
      few: '{n} قطع ليست في قائمة الأسعار، لذا الإجمالي أعلاه غير كامل:',
      many: '{n} قطعة ليست في قائمة الأسعار، لذا الإجمالي أعلاه غير كامل:',
      other: '{n} قطعة ليست في قائمة الأسعار، لذا الإجمالي أعلاه غير كامل:',
    },
    unpricedHint: 'أضفها في الأسعار ← قائمة أسعار المكوّنات وسيكتمل الإجمالي.',
    method: 'الطريقة',
    methodParts: {
      batteryEff: 'كفاءة البطارية',
      systemEff: 'كفاءة النظام',
      sunHours: 'ساعات شمس فعّالة',
      panels: 'واط للوح',
      batteries: 'kWh للبطارية',
    },
    builtInFigures: 'هذه هي الأرقام المضمّنة — انشر إعدادات الأسعار مرة واحدة لتصبح قابلة للتعديل.',
    builtInPrices: 'أسعار المكوّنات من القائمة المضمّنة.',
    customerLive: 'عروض العملاء: الأنظمة التي يتجاوز طلب الإنفرتر فيها',
    customerLiveTail: 'تُسعَّر بهذه الطريقة تلقائيًا.',
    customerWaiting: 'ستتحول عروض العملاء إلى هذه الطريقة للأنظمة فوق',
    customerWaitingTail: 'فور تسعير هذه المكوّنات في قائمة الأسعار:',
    customerMeanwhile: 'حتى ذلك الحين تُسعَّر الأنظمة الكبيرة من قائمة المكوّنات المنزلية — تلقائيًا أيضًا، وبرقم دائمًا.',
    summary: {
      title: 'تحجيم تقريبي — ليس عرض سعر للعميل',
      batteries: 'البطاريات',
      panels: 'الألواح',
      inverter: 'الإنفرتر',
      gross: 'إجمالي',
      array: 'ألواح',
      partsTotal: 'إجمالي القطع التقريبي',
      stillUnpriced: {
        one: 'قطعة واحدة بلا سعر',
        two: 'قطعتان بلا سعر',
        few: '{n} قطع بلا سعر',
        many: '{n} قطعة بلا سعر',
        other: '{n} قطعة بلا سعر',
      },
    },
  },
}

export const ADMIN_BUNDLES: Record<Lang, AdminStrings> = { en: EN, ar: AR }
