/**
 * Every string the admin panel shows, in English and Arabic.
 *
 * Parity is a compile error, not a convention. `EN` is the source of truth,
 * `AdminStrings` is its type, and `AR` is annotated with it — so a key missing
 * from the Arabic bundle fails `tsc`, an extra one is an excess-property error,
 * and nested objects are checked structurally. Inside the maps keyed by an
 * engine id, `satisfies Record<Id, string>` enforces coverage of the id union
 * while keeping the literal keys in the type: add a `WarningId` in
 * pricing/types.ts and BOTH bundles stop compiling until they name it.
 *
 * This is deliberately not the customer bundle. Those strings are reassurance
 * ("our engineer will review this with you") and the admin needs the terse
 * version of the same fact. Where the two overlap — the labels for stored
 * form values — the admin reuses the customer maps instead (see i18n.tsx).
 *
 * Pure data, no React: vitest imports it in Node to walk both trees.
 */
import type { Lang } from '../i18n'
import type { CommercialFlag } from '../pricing/types'
import type { ReferenceCaseId } from '../pricing/referenceCases'
import type { AssumptionId, ConstraintId, EngineResult, SizingMethod, WarningId } from '../pricing/types'
import type { PluralForms } from './format'

export type TabId = 'submissions' | 'pricing' | 'sizing'

type Tier = EngineResult['recommendedTier']
type Confidence = EngineResult['confidence']

/**
 * Identity with a type: it widens the property to `PluralForms` so the Arabic
 * bundle can supply all six CLDR forms where English supplies two.
 */
const plural = (p: PluralForms): PluralForms => p

const EN = {
  common: {
    yes: 'Yes',
    no: 'No',
    dash: '—',
    loading: 'Loading…',
    cancel: 'Cancel',
    delete: 'Delete',
    add: 'Add',
    activate: 'Activate',
    active: 'Active',
    copy: 'Copy summary',
    copied: 'Copied',
    /** Currency word that follows a figure. */
    currency: 'LYD',
    langName: { ar: 'Arabic', en: 'English' } satisfies Record<Lang, string>,
    /** The glyph on the language toggle for each language. */
    langShort: { ar: 'ع', en: 'EN' } satisfies Record<Lang, string>,
    switchTo: { ar: 'Switch to Arabic', en: 'Switch to English' } satisfies Record<Lang, string>,
  },

  app: {
    title: 'Al Qema — Admin',
    signOut: 'Sign out',
    tab: { submissions: 'Leads', pricing: 'Pricing', sizing: 'Sizing' } satisfies Record<TabId, string>,
    tablistLabel: 'Admin sections',
    demoBanner:
      'DEMO MODE — sample data only. These are not real customers, and nothing you change here is saved.',
  },

  login: {
    prompt: 'Sign in with the Google account on the staff list.',
    signingIn: 'Signing in…',
    notStaff: 'This Google account is not on the staff list. Ask the sheet’s owner to add it to the Staff tab.',
    failed: 'Google sign-in did not go through. Try again.',
    unreachable: 'Could not reach the Google Sheet. Check the connection and try again.',
    notConfigured: 'Sign-in is not set up yet. The backend URL and the Google client ID must be filled in (see backend/README.md).',
    googleUnavailable: 'The Google sign-in button could not load. Check the connection, or disable any blocker for accounts.google.com.',
    expired: 'Your session ended. Sign in again.',
  },

  leads: {
    count: plural({ one: '{n} submission', other: '{n} submissions' }),
    exportCsv: 'Export CSV',
    openSheet: 'Open Google Sheet',
    statusHint: 'Status is set by the team in the Google Sheet.',
    showMore: (n: string, remaining: string) => `Show ${n} more (${remaining} remaining)`,
    emptyTitle: 'No submissions yet',
    emptyBody: 'Leads appear here the moment a customer finishes the wizard.',
    loadingList: 'Loading submissions…',
    cols: {
      when: 'When',
      name: 'Name',
      whatsapp: 'WhatsApp',
      city: 'City',
      property: 'Property',
      lang: 'Language',
      tier: 'Tier',
      price: 'Price',
      confidence: 'Confidence',
      status: 'Status',
    },
    siteVisitNoPrice: 'Site visit — no price',
    customPill: 'custom',
    lowConfidencePill: 'low confidence',
    demoPill: 'DEMO DATA',
    openLead: (name: string) => 'Open lead ' + name,
    closeLead: 'Close lead',
    ref: 'ref',
    whatsapp: 'WhatsApp',
  },

  detail: {
    recommendedSystem: 'Recommended system',
    inverter: 'Inverter',
    panels: 'Panels',
    battery: 'Battery',
    nightRuntime: 'Night runtime',
    noNightLoad: 'no night load',
    usable: 'usable',
    yearsShort: 'yr',
    chemistry: { liquid: 'liquid', lithium: 'lithium' } satisfies Record<'liquid' | 'lithium', string>,
    surveyTitle: 'Could not be calculated',
    surveyBody:
      'No system was sized and no price was quoted — the answers produced figures that could not be calculated. Size is never the reason; check the form values.',
    sizingMethod: 'Sizing method',
    method: {
      packages: 'Standard package',
      residentialBom: 'Custom build — household components',
      commercial: 'Commercial method',
    } satisfies Record<SizingMethod, string>,
    engineeringNotes: 'Engineering notes',
    lowConfidenceTitle: 'Low confidence — check before quoting',
    notesTitle: 'Notes',
    assumed: 'Assumed',
    sizedBy: 'Sized by',
    customer: 'Customer',
    phone: 'Phone',
    city: 'City',
    property: 'Property',
    otherPrefix: 'Other — ',
    unspecified: 'unspecified',
    language: 'Language',
    answers: 'Answers',
    dailyCuts: 'Daily cuts',
    keepRunning: 'Keep running',
    nightEconomy: 'Night economy',
    acUnits: 'AC units',
    ac: (n: string) => 'AC ' + n,
    unknownSize: 'unknown size',
    nights: 'nights',
    inverterAc: 'inverter',
    fridge: 'Fridge',
    freezer: 'Freezer',
    alwaysOn: 'always on',
    lighting: 'Lighting',
    bulbs: plural({ one: '{n} bulb', other: '{n} bulbs' }),
    customDevice: 'Custom device',
    systemType: 'System type',
    cutPriority: 'Cut priority',
    roof: 'Roof',
    shade: 'shade',
    customerNotes: 'Customer notes',
    loadAudit: 'Load audit',
    perDay: 'kWh/day',
    nightKwh: 'kWh night',
    peakKw: 'kW peak',
    loadCols: {
      load: 'Load',
      avgW: 'Avg W',
      peakW: 'Peak W',
      qty: 'Qty',
      hoursPerDay: 'h/day',
      night: 'Night',
      assumed: 'Assumed',
    },
    hoursPerDay: 'h/day',
    nightPill: 'night',
    assumedPill: 'assumed',
    customBuild: 'Custom build (internal)',
    bomCols: { component: 'Component', qty: 'Qty', unit: 'Unit', total: 'Total' },
    partsSubtotal: 'Parts subtotal',
    quoted: 'Quoted',
    floorApplied: 'floor applied',
  },

  labels: {
    warning: {
      heavyDutyLoad: 'Heavy appliance in the load list',
      acBtuExceeded: 'An AC exceeds this tier’s BTU cap',
      customFloorApplied: 'Priced at the custom-build floor, not the parts total',
      roofSpaceTight: 'Array may not fit the roof the customer described',
    } satisfies Record<WarningId, string>,
    assumption: {
      acSizeAssumed: 'AC size (customer did not know)',
      lightingAssumed: 'Bulb wattage',
      customApplianceAssumed: 'Power of a custom device',
      usageHoursAssumed: 'Daily running hours',
    } satisfies Record<AssumptionId, string>,
    constraint: {
      inverter: 'inverter power',
      battery: 'battery storage',
      panels: 'panel count',
      acCount: 'number of ACs',
      acBtu: 'AC size (BTU)',
    } satisfies Record<ConstraintId, string>,
    flag: {
      residentialScale:
        'This is a household-sized load. The smallest stocked inverter is far bigger than it needs — quote it from the packages instead.',
      aboveLargestInverter:
        'The peak load is above the largest stocked inverter, so the size shown is capped. This job needs multiple units and an engineer.',
      dcAcRatioHigh:
        'The array is much larger than the inverter the method selects. The method sizes the inverter from the daytime load alone, but the array also has to recharge the battery bank — confirm whether the inverter carries the charging, or whether separate charge controllers do.',
    } satisfies Record<CommercialFlag, string>,
    tier: {
      S: 'S',
      M: 'M',
      L: 'L',
      XL: 'XL',
      XXL: 'XXL',
      CUSTOM: 'Custom',
      SURVEY: 'Survey',
    } satisfies Record<Tier, string>,
    confidence: { high: 'high', low: 'low' } satisfies Record<Confidence, string>,
    /** Short property labels so the card meta line stays on one line at 390px. */
    propertyShort: {
      Home: 'Home',
      'Office / Company': 'Office',
      Shop: 'Shop',
      Clinic: 'Clinic',
      Workshop: 'Workshop',
      Other: 'Other',
    } as Record<string, string>,
  },

  csv: {
    date: 'Date',
    name: 'Name',
    whatsapp: 'WhatsApp',
    city: 'City',
    property: 'Property',
    language: 'Language',
    tier: 'Tier',
    priceLyd: 'Price (LYD)',
    custom: 'Custom',
    confidence: 'Confidence',
    pricingRef: 'Pricing ref',
  },

  pricing: {
    loading: 'Loading pricing config…',
    loadFailed: 'Could not read the published prices from the Google Sheet.',
    retry: 'Try again',
    unpublishedTitle: 'No prices published yet',
    unpublishedBody:
      'The site is using the built-in prices. Publish them once to start the version history in the Google Sheet — or edit them first.',
    publishBuiltIn: 'Publish the built-in prices',
    intro:
      'The prices customers see. Package prices are fixed; anything beyond the packages is priced from the component list. Nothing goes live until you review and publish.',

    /* ---- Prices page ---- */
    packagePrices: 'Package prices',
    packagePricesBlurb:
      'One price per package. The summary is what the package contains — to change the hardware, open Advanced.',
    editHardware: 'Edit hardware',
    noAc: 'no AC',
    upToAcs: plural({ one: 'up to {n} AC', other: 'up to {n} ACs' }),
    usable: 'usable',
    customSystems: 'Custom and large systems',
    customSystemsBlurb:
      'When no package fits, the price is built from the component list and rounded up. The minimum price stops a custom build undercutting XXL.',
    minimumPrice: 'Minimum price',
    roundUpHousehold: 'Round up to — household builds',
    roundUpCommercial: 'Round up to — large systems',
    oneOffItems: 'One-off items on every build',
    perPanelAllIn: 'Each panel, all-in',
    perInverterAllIn: 'Each extra inverter, all-in',
    addOns: 'Add-ons',
    addOnsBlurb: 'Optional extras offered with every quote.',
    addOnName: 'Name',
    addAddOn: 'Add an add-on',
    removeAddOn: (name: string) => 'Remove ' + name,
    noAddOns: 'No add-ons.',

    /* ---- Component prices ---- */
    componentPrices: 'Component prices',
    componentPricesBlurb:
      'Unit prices for custom builds. Changing one moves every custom quote that uses it — the review shows by how much.',
    search: 'Search components',
    noMatches: 'No components match.',
    category: {
      commercialInverters: 'Large-system inverters',
      inverters: 'Inverters',
      batteries: 'Batteries',
      panels: 'Panels',
      mounting: 'Mounting & cabling',
      services: 'Services',
      misc: 'Other',
    },
    categoryNote: 'Grouped by name for reading only; a group does not change how a part is priced.',
    usedBy: {
      household: 'household build',
      commercial: 'large systems',
      both: 'household & large',
      none: 'not used by any build',
    },
    unpricedTitle: plural({
      one: '{n} part the large-system method needs has no price yet',
      other: '{n} parts the large-system method needs have no price yet',
    }),
    unpricedBlurb: (kw: string) =>
      `Customer quotes for systems above ${kw} kW switch to Al Qema’s commercial method automatically once every part here has a price. Until then they are priced from the household component list.`,
    noPrice: 'no price',
    pricePlaceholder: 'price',
    newComponent: 'New component',
    newComponentName: 'Name',
    priceRequired: 'Enter a price to add it.',
    nameTaken: 'A component with this name already exists.',
    rename: 'Rename',
    renameTo: 'New name',
    deleteBlocked: 'Used by a build recipe — change the recipe first.',
    removeComponent: (name: string) => 'Remove ' + name,

    /* ---- Advanced ---- */
    advanced: 'Advanced',
    advancedBlurb: 'Hardware, assumptions and constants. Most days nobody needs these.',
    show: 'Show',
    hide: 'Hide',
    sections: {
      hardware: 'Package hardware',
      recipe: 'Custom build recipe',
      appliances: 'Appliance assumptions',
      household: 'Household sizing',
      commercial: 'Large-system method',
    },
    sectionBlurb: {
      hardware:
        'What each package contains. Together with the sizing constants this decides which package a customer is offered.',
      recipe: 'How a system beyond the packages is built and priced from the component list.',
      appliances:
        'The power and hours assumed for each device a customer can tick. These feed every quote.',
      household: 'The constants behind every household quote. Change with care — the review will show the effect.',
      commercial: 'Al Qema’s method for large installations, used automatically above the hand-over size.',
    },
    hardware: {
      inverter: 'Inverter',
      panels: 'Panels',
      panelWatts: 'Watts per panel',
      batteryType: 'Battery type',
      batteries: 'Batteries',
      ahEach: 'Ah each',
      kwhEach: 'kWh each',
      maxAcs: 'Max ACs',
      maxAcBtu: 'Max AC size',
      maxAcBtuHelp: 'Leave empty to skip the size check.',
      array: 'array',
      inverterKw: 'inverter',
    },
    recipe: {
      panel: 'Panel',
      battery: 'Battery',
      singleInverter: 'Single inverter — up to',
      parallelInverter: 'Parallel inverters — each',
      stand: 'Stand',
      panelsPerStand: 'Panels per stand',
      perPanel: 'Per panel',
      perInverter: 'Per inverter',
      fixed: 'One-off items',
      part: 'Part',
      qty: 'Qty',
      addLine: 'Add line',
      removeLine: 'Remove line',
      derived: 'What this adds up to',
    },
    appliances: {
      appliance: 'Appliance',
      watts: 'Watts',
      hoursPerDay: 'Hours per day',
      night: 'Runs at night',
      alwaysOn: 'Always on',
      heavy: 'heavy',
      otherDevice: 'Default for a device the customer types in',
      lighting: 'Lighting',
      bulbWatts: { led: 'LED bulb', regular: 'Regular bulb', mixed: 'Mixed' },
      lightingHours: 'Lighting hours per day',
      cold: 'Fridge & freezer',
      fridgeWatts: 'Fridge watts',
      freezerWatts: 'Freezer watts',
      duty: 'Share of time running (0–1)',
      ac: 'Air conditioning',
      acStandard: 'Watts per BTU — standard AC',
      acInverter: 'Watts per BTU — inverter AC',
      assumedAcBtu: 'Assumed size when the customer does not know',
    },
    household: {
      sun: 'Sun & losses',
      peakSunHours: 'Peak sun hours per day',
      peakSunHoursHelp: 'Fewer hours means more panels for the same load.',
      systemEfficiency: 'System efficiency (0–1)',
      systemEfficiencyHelp: 'Losses in wiring, heat and dust. Lower means more panels.',
      battery: 'Battery',
      dodLiquid: 'Usable share — liquid (0–1)',
      dodLithium: 'Usable share — lithium (0–1)',
      liquidVolts: 'Liquid battery voltage',
      nightHours: 'Hours the battery must carry the night load',
      lifespan: 'Battery lifespan shown to customers (years)',
      inverter: 'Inverter',
      safetyFactor: 'Safety margin on peak load',
      safetyFactorHelp: '1.25 sizes the inverter 25% above the peak.',
      diversityFactor: 'Diversity factor (0–1)',
      diversityFactorHelp: 'Not everything runs at once; 0.8 assumes 80% of the peak.',
      kvaToKw: 'Power factor (kW per kVA)',
      surge: 'Start-up surge multipliers',
      surgeHelp: 'Compressors draw more than their average when they start.',
      ac: 'Air conditioning',
      acBtuCapMode: 'When an AC is bigger than the package allows',
      acBtuCapModeOptions: {
        advisory: 'Warn, but still offer the package',
        strict: 'Move the customer up a package',
      },
      roof: 'Roof',
      panelArea: 'Roof area per panel (m²)',
      roofArea: 'Usable roof area by answer (m²)',
      roofAreaHelp: 'Zero disables the check for that answer.',
    },
    commercial: {
      constants: 'Constants',
      batteryEfficiency: 'Battery efficiency (0–1)',
      systemEfficiency: 'System efficiency (0–1)',
      peakSunHours: 'Peak sun hours per day',
      maxDcAcRatio: 'Flag when array ÷ inverter exceeds',
      parts: 'Parts',
      panel: 'Panel',
      battery: 'Battery',
      stand: 'Stand',
      ladder: 'Inverter sizes stocked',
      priced: 'priced',
      addPrice: 'Add price',
      handOver: 'Hand systems to this method above (kW)',
      handOverHelp: 'Inverter demand after the safety margin. Below it, parallel household inverters are used.',
      quantitiesFixed: 'Line quantities are fixed until the client confirms them.',
    },
    notEditable:
      'Not editable here: currency, version number, the BTU-per-ton conversion, fridge-condition multipliers, future loads, the “included” list and the large-system parts quantities.',
    heading: (n: number) => `${n}`,

    /* ---- bar, review, outcomes, history ---- */
    reviewLabel: 'Review changes',
    reviewChanges: plural({ one: 'Review {n} change', other: 'Review {n} changes' }),
    changesCount: plural({ one: '{n} change', other: '{n} changes' }),
    problemsCount: plural({ one: '{n} problem', other: '{n} problems' }),
    showProblem: 'Show',
    fixFirst: 'Fix the problems before reviewing.',
    noChanges: 'No changes',
    discard: 'Discard changes',
    problemsTitle: 'Problems in this draft',
    review: {
      title: 'Review before publishing',
      rollbackTitle: 'Activate an older version',
      close: 'Close',
      whatChanged: 'What changed',
      effect: 'What it does to real quotes',
      effectBlurb: 'Seven reference households, priced with what is live now and with this draft.',
      household: 'Household',
      live: 'Live now',
      draft: 'After publishing',
      noChange: 'no change',
      changedCount: (n: string, total: string) => `${n} of ${total} households change`,
      noneChange:
        'None of the reference households change. That is expected for a rarely used value, or a hardware edit that does not move a package boundary.',
      cannotPrice: 'cannot be priced',
      problems: 'Problems',
      problemsBlurb: 'Publishing is blocked until these are fixed.',
      publishAs: 'Publish as',
      publishing: 'Publishing…',
      activate: 'Activate',
      activating: 'Activating…',
      arrow: '→',
      empty: 'empty',
      unsavedWarning: 'You have unsaved edits. Activating an older version discards them.',
      discardAndContinue: 'Discard my edits and continue',
      invalidVersion:
        'This version cannot be activated: it no longer passes the current checks. Publish a corrected draft instead.',
      compareTo: (v: string) => `Compared against what is live now, ${v} would change:`,
    },
    outcome: {
      published: (v: string) => `Published ${v} — live for new visitors now.`,
      activated: (v: string) => `Activated ${v}.`,
      failed: 'Nothing was saved — the Google Sheet could not take the new version:',
      activateFailed: 'Could not activate this version:',
      invalid: 'The draft failed a final check and was not saved.',
    },
    history: {
      title: 'Version history',
      liveNow: 'Live now',
      activate: 'Activate…',
      loading: 'Loading…',
    },
    /** The reference households re-priced before every publish. */
    referenceCase: {
      smallFlat: 'Small flat',
      familyHomeOneAc: 'Family home, one AC',
      homeAcAndFreezer: 'Home, AC and freezer',
      homeTwoAcs: 'Home with two ACs',
      shop: 'Shop',
      largeVilla: 'Large villa',
      workshop: 'Workshop',
    } satisfies Record<ReferenceCaseId, string>,
    /**
     * Human labels for config paths and validator reasons. The validator
     * speaks in `packages[2].priceLyd: must be a positive number`; a manager
     * reads "Packages · L package · price (LYD) — must be a number above 0".
     */
    paths: {
      section: {
        configVersion: 'Version',
        currency: 'Currency',
        acBtuCapMode: 'Oversized-AC behaviour',
        packages: 'Packages',
        includes: 'Included items',
        addOns: 'Add-ons',
        batteryLifespanYears: 'Battery lifespan (years)',
        components: 'Component prices',
        loadDefaults: 'Appliance assumptions',
        sizing: 'Household sizing',
        customBom: 'Custom build',
        commercial: 'Large-system method',
      } as Record<string, string>,
      field: {
        tier: 'tier',
        inverterKva: 'inverter (kVA)',
        panel: 'panels',
        count: 'count',
        watts: 'watts (W)',
        battery: 'battery',
        chemistry: 'battery type',
        ampHours: 'capacity (Ah)',
        kwhEach: 'capacity each (kWh)',
        maxAcUnits: 'max ACs',
        maxAcBtu: 'max AC size (BTU)',
        priceLyd: 'price (LYD)',
        name: 'name',
        liquid: 'liquid',
        lithium: 'lithium',
        acWattsPerBtu: 'AC watts per BTU',
        standard: 'standard',
        inverter: 'inverter',
        assumedAcBtu: 'assumed AC size when unknown (BTU)',
        btuPerTon: 'BTU per ton',
        lightingWattsByType: 'bulb wattage by type (W)',
        led: 'LED',
        regular: 'regular',
        mixed: 'mixed',
        lightingHours: 'lighting hours per day',
        fridge: 'fridge',
        freezer: 'freezer',
        duty: 'duty cycle',
        fridgeConditionMultiplier: 'fridge condition multiplier',
        new: 'new',
        old: 'old',
        defaultFridgeCondition: 'default fridge condition',
        appliancesByName: 'appliances',
        hours: 'hours per day',
        night: 'runs at night',
        alwaysOn: 'always on',
        customAppliance: '“other device” default',
        peakSunHours: 'peak sun hours (h)',
        systemEfficiency: 'system efficiency',
        inverterSafetyFactor: 'inverter safety factor',
        diversityFactor: 'diversity factor',
        liquidBatteryVoltageV: 'liquid battery voltage (V)',
        kvaToKw: 'power factor (kW per kVA)',
        alwaysOnNightHours: 'night hours (h)',
        dodByChemistry: 'depth of discharge',
        surgeFactorByCategory: 'surge factors',
        ac: 'AC',
        cold: 'fridges & freezers',
        lighting: 'lighting',
        appliance: 'other appliances',
        panelAreaM2: 'area per panel (m²)',
        roofAreaM2ByAnswer: 'roof area by answer (m²)',
        single: 'single inverter',
        parallel: 'parallel inverter',
        maxKw: 'max (kW)',
        unitKw: 'each (kW)',
        component: 'part',
        stand: 'stand',
        panelsPerStand: 'panels per stand',
        perPanel: 'per-panel items',
        perInverter: 'per-inverter items',
        fixed: 'one-off items',
        qty: 'quantity',
        roundUpToLyd: 'round up to (LYD)',
        minimumLyd: 'minimum price (LYD)',
        batteryEfficiency: 'battery efficiency',
        inverterLadder: 'inverter sizes',
        kw: 'size (kW)',
        maxDcAcRatio: 'max DC:AC ratio',
        customerPath: 'customer quotes',
        takesOverAboveKw: 'commercial method above (kW)',
      } as Record<string, string>,
      packageItem: (tier: string) => `${tier} package`,
      listItem: (n: number) => `item ${n}`,
      ladderItem: (n: number) => `size ${n}`,
      reason: {
        positive: 'must be a number above 0',
        nonNegative: 'must be 0 or more',
        wholeNumber: 'must be a whole number, 0 or more',
        between: (min: string, max: string) => `must be between ${min} and ${max}`,
        fraction: 'must be above 0 and at most 1',
        positiveOrEmpty: 'must be empty or a number above 0',
        monotonic: 'package prices must not go down from S to XXL',
        floorBelowXxl: (n: string) => `must be at least the XXL price (${n}), or custom builds would undercut it`,
        unknownComponent: 'names a part that is not in the component price list',
        missingPreset: (name: string) => `the form offers “${name}”, so it needs a power figure`,
        ascending: 'sizes must go from small to large',
        atLeastOne: 'needs at least one entry',
        needsName: 'needs a part name',
        emptyName: 'one component has an empty name',
        addOn: 'every add-on needs a name and a price above 0',
        chemistry: 'must be liquid or lithium',
        acBtuCapMode: 'must be “warn but still offer the package” or “move the customer up a package”',
        newOrOld: 'must be new or old',
        liquidBattery: 'a liquid battery needs a whole-number count above 0 and Ah above 0',
        lithiumBattery: 'a lithium battery needs a whole-number count above 0 and kWh above 0',
        panelSpec: 'needs a whole-number panel count above 0 and watts above 0',
        wattsDuty: 'needs watts above 0 and a duty cycle above 0 and at most 1',
        wattsHours: 'needs watts above 0 and hours 0 or more',
        watts: 'needs watts above 0',
        hours24: 'must be between 0 and 24 hours',
        pairPositive: 'both values must be above 0',
        allPositive: 'every value must be above 0',
        dodPair: 'liquid and lithium must each be above 0 and at most 1',
        lifespanPair: 'liquid and lithium must both be above 0',
        surge: 'each surge factor must be between 1 and 10',
        panelArea: 'must be above 0 and under 20 m²',
        roofAreas: 'every roof area must be 0 m² or more',
        componentAndWatts: 'needs a part from the price list and watts above 0',
        componentAndKwh: 'needs a part from the price list and kWh above 0',
        inverterParts: 'both inverters need a part from the price list and a kW rating above 0',
        standParts: 'needs a part from the price list and a whole number of panels per stand above 0',
        qty: 'needs a quantity above 0',
        kwAndName: 'needs a size in kW above 0 and a part name',
        ratio: 'must be at least 1',
        structural: 'this part of the config is not in the expected shape — reload the page before editing',
      },
    },
  },

  sizing: {
    banner:
      'Internal estimate — not a customer quote. Sized with Al Qema’s commercial method; prices are indicative and every figure needs an engineer’s sign-off.',
    job: 'The job',
    batteryKwh: 'Daily battery energy (kWh)',
    dayLoadKw: 'Daytime load (kW)',
    peakKw: 'Peak load (kW)',
    help: 'Battery energy is what has to come out of the bank overnight. Daytime load is what the panels carry directly. Peak defaults to the daytime load.',
    usingPeak: 'Using',
    checkNumbers: 'Check the numbers',
    system: 'System',
    batteries: 'batteries',
    arrayCaption: 'array',
    inverter: 'inverter',
    steps: {
      gross: 'gross energy, then batteries',
      recharge: 'to recharge the bank',
      array: 'array, then panels',
      inverter: 'inverter from the peak load',
    },
    loadPlusCharging: 'load + charging would be',
    checkBeforeQuoting: 'Check before quoting',
    partsList: 'Indicative parts list',
    cols: { item: 'Item', qty: 'Qty', unit: 'Unit', total: 'Total' },
    noPrice: 'no price',
    pricedRounded: 'Priced items, rounded up',
    unpricedNote: plural({
      one: '{n} item is not in the price list, so the total above is incomplete:',
      other: '{n} items are not in the price list, so the total above is incomplete:',
    }),
    unpricedHint: 'Add them in Pricing → Component prices — they are pinned at the top — and this fills in.',
    method: 'Method',
    methodParts: {
      batteryEff: 'battery efficiency',
      systemEff: 'system efficiency',
      sunHours: 'peak sun hours',
      panels: 'W panels',
      batteries: 'kWh batteries',
    },
    builtInFigures:
      'These are the built-in figures — publish the pricing config once to make them editable.',
    builtInPrices: 'Component prices are the built-in list.',
    customerLive: 'Customer quotes: systems above',
    customerLiveTail: 'of inverter demand are priced by this method automatically.',
    customerWaiting: 'Customer quotes will switch to this method for systems above',
    customerWaitingTail: 'as soon as these are priced in the component list:',
    customerMeanwhile: 'Until then large systems are priced from the household component list — still automatically, still with a number.',
    summary: {
      title: 'Indicative sizing — not a customer quote',
      batteries: 'Batteries',
      panels: 'Panels',
      inverter: 'Inverter',
      gross: 'gross',
      array: 'array',
      partsTotal: 'Indicative parts total',
      stillUnpriced: plural({
        one: '{n} item still unpriced',
        other: '{n} items still unpriced',
      }),
    },
  },
}

export type AdminStrings = typeof EN

export const AR: AdminStrings = {
  common: {
    yes: 'نعم',
    no: 'لا',
    dash: '—',
    loading: 'جارٍ التحميل…',
    cancel: 'إلغاء',
    delete: 'حذف',
    add: 'إضافة',
    activate: 'تفعيل',
    active: 'مفعّل',
    copy: 'نسخ الملخص',
    copied: 'تم النسخ',
    currency: 'د.ل',
    langName: { ar: 'العربية', en: 'الإنجليزية' },
    langShort: { ar: 'ع', en: 'EN' },
    switchTo: { ar: 'التبديل إلى العربية', en: 'التبديل إلى الإنجليزية' },
  },

  app: {
    title: 'القمة — لوحة الإدارة',
    signOut: 'تسجيل الخروج',
    tab: { submissions: 'الطلبات', pricing: 'الأسعار', sizing: 'التحجيم' },
    tablistLabel: 'أقسام لوحة الإدارة',
    demoBanner:
      'وضع العرض التجريبي — بيانات تجريبية فقط. هؤلاء ليسوا عملاء حقيقيين، ولا يُحفظ أي تغيير هنا.',
  },

  login: {
    prompt: 'سجّل الدخول بحساب Google المدرج في قائمة الموظفين.',
    signingIn: 'جارٍ تسجيل الدخول…',
    notStaff: 'حساب Google هذا ليس في قائمة الموظفين. اطلب من مالك الجدول إضافته إلى ورقة Staff.',
    failed: 'لم يكتمل تسجيل الدخول عبر Google. حاول مجددًا.',
    unreachable: 'تعذّر الوصول إلى جدول Google. تحقّق من الاتصال وحاول مجددًا.',
    notConfigured: 'تسجيل الدخول غير مُعدّ بعد. يجب إدخال رابط الخادم ومعرّف عميل Google (راجع backend/README.md).',
    googleUnavailable: 'تعذّر تحميل زر تسجيل الدخول عبر Google. تحقّق من الاتصال أو عطّل أي مانع لـ accounts.google.com.',
    expired: 'انتهت جلستك. سجّل الدخول مجددًا.',
  },

  leads: {
    count: {
      zero: 'لا طلبات',
      one: 'طلب واحد',
      two: 'طلبان',
      few: '{n} طلبات',
      many: '{n} طلبًا',
      other: '{n} طلب',
    },
    exportCsv: 'تصدير CSV',
    openSheet: 'فتح جدول Google',
    statusHint: 'يحدّد الفريق الحالة في جدول Google.',
    showMore: (n, remaining) => `عرض ${n} أخرى (${remaining} متبقية)`,
    emptyTitle: 'لا توجد طلبات بعد',
    emptyBody: 'تظهر الطلبات هنا فور إكمال العميل للنموذج.',
    loadingList: 'جارٍ تحميل الطلبات…',
    cols: {
      when: 'الوقت',
      name: 'الاسم',
      whatsapp: 'واتساب',
      city: 'المدينة',
      property: 'نوع المكان',
      lang: 'اللغة',
      tier: 'الباقة',
      price: 'السعر',
      confidence: 'الثقة',
      status: 'الحالة',
    },
    siteVisitNoPrice: 'معاينة الموقع — بدون سعر',
    customPill: 'مخصّص',
    lowConfidencePill: 'ثقة منخفضة',
    demoPill: 'بيانات تجريبية',
    openLead: (name) => 'فتح الطلب ' + name,
    closeLead: 'إغلاق الطلب',
    ref: 'مرجع',
    whatsapp: 'واتساب',
  },

  detail: {
    recommendedSystem: 'النظام المقترح',
    inverter: 'الإنفرتر',
    panels: 'الألواح',
    battery: 'البطارية',
    nightRuntime: 'مدة التشغيل الليلي',
    noNightLoad: 'لا حمل ليلي',
    usable: 'قابل للاستخدام',
    yearsShort: 'سنة',
    chemistry: { liquid: 'سائلة', lithium: 'ليثيوم' },
    surveyTitle: 'لم يمكن حسابه',
    surveyBody:
      'لم يُحدَّد نظام ولم يُعرض سعر — أنتجت الإجابات أرقامًا لا يمكن حسابها. الحجم ليس السبب أبدًا؛ راجع قيم النموذج.',
    sizingMethod: 'طريقة التحجيم',
    method: {
      packages: 'باقة قياسية',
      residentialBom: 'تركيبة مخصّصة — مكوّنات منزلية',
      commercial: 'الطريقة التجارية',
    },
    engineeringNotes: 'ملاحظات هندسية',
    lowConfidenceTitle: 'ثقة منخفضة — راجع قبل التسعير',
    notesTitle: 'ملاحظات',
    assumed: 'مُفترَض',
    sizedBy: 'حُدِّد الحجم حسب',
    customer: 'العميل',
    phone: 'الهاتف',
    city: 'المدينة',
    property: 'نوع المكان',
    otherPrefix: 'أخرى — ',
    unspecified: 'غير محدد',
    language: 'اللغة',
    answers: 'الإجابات',
    dailyCuts: 'ساعات الانقطاع',
    keepRunning: 'ما يجب تشغيله',
    nightEconomy: 'الاقتصاد الليلي',
    acUnits: 'عدد المكيفات',
    ac: (n) => 'مكيف ' + n,
    unknownSize: 'قدرة غير معروفة',
    nights: 'ليلًا',
    inverterAc: 'إنفرتر',
    fridge: 'الثلاجة',
    freezer: 'الفريزر',
    alwaysOn: 'يعمل دائمًا',
    lighting: 'الإنارة',
    bulbs: {
      zero: 'لا مصابيح',
      one: 'مصباح واحد',
      two: 'مصباحان',
      few: '{n} مصابيح',
      many: '{n} مصباحًا',
      other: '{n} مصباح',
    },
    customDevice: 'جهاز مخصّص',
    systemType: 'نوع النظام',
    cutPriority: 'الأولوية عند الانقطاع',
    roof: 'السطح',
    shade: 'الظل',
    customerNotes: 'ملاحظات العميل',
    loadAudit: 'تفصيل الأحمال',
    perDay: 'ك.و.س/يوم',
    nightKwh: 'ك.و.س ليلًا',
    peakKw: 'ك.و ذروة',
    loadCols: {
      load: 'الحمل',
      avgW: 'واط متوسط',
      peakW: 'واط ذروة',
      qty: 'العدد',
      hoursPerDay: 'س/يوم',
      night: 'ليلي',
      assumed: 'مُفترَض',
    },
    hoursPerDay: 'س/يوم',
    nightPill: 'ليلي',
    assumedPill: 'مُفترَض',
    customBuild: 'التركيبة المخصّصة (داخلي)',
    bomCols: { component: 'المكوّن', qty: 'العدد', unit: 'سعر الوحدة', total: 'الإجمالي' },
    partsSubtotal: 'مجموع القطع',
    quoted: 'السعر المعروض',
    floorApplied: 'طُبِّق الحد الأدنى',
  },

  labels: {
    warning: {
      heavyDutyLoad: 'جهاز ثقيل في قائمة الأحمال',
      acBtuExceeded: 'مكيف يتجاوز حد BTU لهذه الباقة',
      customFloorApplied: 'سُعِّر بالحد الأدنى للتركيبة المخصّصة، لا بمجموع القطع',
      roofSpaceTight: 'قد لا تتسع الألواح على السطح الذي وصفه العميل',
    },
    assumption: {
      acSizeAssumed: 'قدرة المكيف (العميل لا يعرفها)',
      lightingAssumed: 'قدرة المصابيح',
      customApplianceAssumed: 'قدرة جهاز مخصّص',
      usageHoursAssumed: 'ساعات التشغيل اليومية',
    },
    constraint: {
      inverter: 'قدرة الإنفرتر',
      battery: 'سعة البطاريات',
      panels: 'عدد الألواح',
      acCount: 'عدد المكيفات',
      acBtu: 'قدرة المكيف (BTU)',
    },
    flag: {
      residentialScale:
        'هذا حمل بحجم منزلي. أصغر إنفرتر متوفر أكبر بكثير مما يلزم — سعِّره من الباقات بدلًا من ذلك.',
      aboveLargestInverter:
        'حمل الذروة أعلى من أكبر إنفرتر متوفر، لذا القدرة المعروضة محدودة بالحد الأقصى. يحتاج هذا المشروع إلى عدة وحدات وإلى مهندس.',
      dcAcRatioHigh:
        'الألواح أكبر بكثير من الإنفرتر الذي تختاره الطريقة. الطريقة تحدد الإنفرتر من حمل النهار فقط، بينما يجب أن تشحن الألواح البطاريات أيضًا — تأكد هل الإنفرتر يتحمل الشحن، أم تتولاه منظمات شحن منفصلة.',
    },
    tier: {
      S: 'S',
      M: 'M',
      L: 'L',
      XL: 'XL',
      XXL: 'XXL',
      CUSTOM: 'مخصّص',
      SURVEY: 'معاينة',
    },
    confidence: { high: 'عالية', low: 'منخفضة' },
    propertyShort: {
      Home: 'منزل',
      'Office / Company': 'مكتب',
      Shop: 'محل',
      Clinic: 'عيادة',
      Workshop: 'ورشة',
      Other: 'أخرى',
    },
  },

  csv: {
    date: 'التاريخ',
    name: 'الاسم',
    whatsapp: 'واتساب',
    city: 'المدينة',
    property: 'نوع المكان',
    language: 'اللغة',
    tier: 'الباقة',
    priceLyd: 'السعر (د.ل)',
    custom: 'مخصّص',
    confidence: 'الثقة',
    pricingRef: 'مرجع التسعير',
  },

  pricing: {
    loading: 'جارٍ تحميل إعدادات الأسعار…',
    loadFailed: 'تعذّرت قراءة الأسعار المنشورة من جدول Google.',
    retry: 'حاول مجددًا',
    unpublishedTitle: 'لم تُنشر أي أسعار بعد',
    unpublishedBody:
      'الموقع يستخدم الأسعار المدمجة. انشرها مرة واحدة لبدء سجل الإصدارات في جدول Google — أو عدّلها أولًا.',
    publishBuiltIn: 'نشر الأسعار المدمجة',
    intro:
      'الأسعار التي يراها العملاء. أسعار الباقات ثابتة؛ وما يتجاوز الباقات يُسعَّر من قائمة المكوّنات. لا يسري شيء حتى تراجع وتنشر.',

    packagePrices: 'أسعار الباقات',
    packagePricesBlurb: 'سعر واحد لكل باقة. الملخّص هو ما تحتويه الباقة — لتغيير العتاد افتح «متقدّم».',
    editHardware: 'تعديل العتاد',
    noAc: 'بدون مكيف',
    upToAcs: {
      zero: 'بدون مكيف',
      one: 'حتى مكيف واحد',
      two: 'حتى مكيفين',
      few: 'حتى {n} مكيفات',
      many: 'حتى {n} مكيفًا',
      other: 'حتى {n} مكيف',
    },
    usable: 'قابلة للاستخدام',
    customSystems: 'الأنظمة المخصّصة والكبيرة',
    customSystemsBlurb:
      'عندما لا تناسب أي باقة، يُبنى السعر من قائمة المكوّنات ويُقرَّب لأعلى. الحد الأدنى يمنع أن يقل النظام المخصّص عن باقة XXL.',
    minimumPrice: 'الحد الأدنى للسعر',
    roundUpHousehold: 'التقريب لأعلى إلى — الأنظمة المنزلية',
    roundUpCommercial: 'التقريب لأعلى إلى — الأنظمة الكبيرة',
    oneOffItems: 'البنود الثابتة في كل نظام',
    perPanelAllIn: 'كل لوح بملحقاته',
    perInverterAllIn: 'كل إنفرتر إضافي بملحقاته',
    addOns: 'الإضافات',
    addOnsBlurb: 'خيارات إضافية تُعرض مع كل عرض سعر.',
    addOnName: 'الاسم',
    addAddOn: 'إضافة خيار',
    removeAddOn: (name) => 'حذف ' + name,
    noAddOns: 'لا إضافات.',

    componentPrices: 'أسعار المكوّنات',
    componentPricesBlurb:
      'أسعار الوحدة للأنظمة المخصّصة. تغيير سعر واحد يحرّك كل عرض مخصّص يستخدمه — والمراجعة تُظهر مقدار التغيير.',
    search: 'ابحث في المكوّنات',
    noMatches: 'لا مكوّنات مطابقة.',
    category: {
      commercialInverters: 'إنفرترات الأنظمة الكبيرة',
      inverters: 'الإنفرترات',
      batteries: 'البطاريات',
      panels: 'الألواح',
      mounting: 'التثبيت والكوابل',
      services: 'الخدمات',
      misc: 'أخرى',
    },
    categoryNote: 'التجميع حسب الاسم للقراءة فقط؛ لا يغيّر طريقة تسعير القطعة.',
    usedBy: {
      household: 'النظام المنزلي',
      commercial: 'الأنظمة الكبيرة',
      both: 'المنزلي والكبير',
      none: 'لا يستخدمه أي نظام',
    },
    unpricedTitle: {
      one: 'قطعة واحدة تحتاجها طريقة الأنظمة الكبيرة بلا سعر بعد',
      two: 'قطعتان تحتاجهما طريقة الأنظمة الكبيرة بلا سعر بعد',
      few: '{n} قطع تحتاجها طريقة الأنظمة الكبيرة بلا سعر بعد',
      many: '{n} قطعة تحتاجها طريقة الأنظمة الكبيرة بلا سعر بعد',
      other: '{n} قطعة تحتاجها طريقة الأنظمة الكبيرة بلا سعر بعد',
    },
    unpricedBlurb: (kw) =>
      `عروض العملاء للأنظمة فوق ${kw} kW تتحوّل تلقائيًا إلى طريقة القمة التجارية حين يصبح لكل قطعة هنا سعر. وحتى ذلك الحين تُسعَّر من قائمة المكوّنات المنزلية.`,
    noPrice: 'بلا سعر',
    pricePlaceholder: 'السعر',
    newComponent: 'مكوّن جديد',
    newComponentName: 'الاسم',
    priceRequired: 'أدخل سعرًا لإضافته.',
    nameTaken: 'يوجد مكوّن بهذا الاسم.',
    rename: 'إعادة تسمية',
    renameTo: 'الاسم الجديد',
    deleteBlocked: 'مستخدم في وصفة نظام — غيّر الوصفة أولًا.',
    removeComponent: (name) => 'حذف ' + name,

    advanced: 'متقدّم',
    advancedBlurb: 'العتاد والافتراضات والثوابت. في معظم الأيام لا يحتاجها أحد.',
    show: 'عرض',
    hide: 'إخفاء',
    sections: {
      hardware: 'عتاد الباقات',
      recipe: 'وصفة النظام المخصّص',
      appliances: 'افتراضات الأجهزة',
      household: 'تحجيم المنازل',
      commercial: 'طريقة الأنظمة الكبيرة',
    },
    sectionBlurb: {
      hardware: 'ما تحتويه كل باقة. مع ثوابت التحجيم يحدّد هذا الباقة التي تُعرض على العميل.',
      recipe: 'كيف يُبنى ويُسعَّر نظام يتجاوز الباقات من قائمة المكوّنات.',
      appliances: 'القدرة والساعات المفترضة لكل جهاز يمكن للعميل اختياره. تدخل في كل عرض سعر.',
      household: 'الثوابت خلف كل عرض منزلي. غيّرها بحذر — المراجعة ستُظهر الأثر.',
      commercial: 'طريقة القمة للمنشآت الكبيرة، تُستخدم تلقائيًا فوق حجم التحويل.',
    },
    hardware: {
      inverter: 'الإنفرتر',
      panels: 'الألواح',
      panelWatts: 'واط لكل لوح',
      batteryType: 'نوع البطارية',
      batteries: 'البطاريات',
      ahEach: 'Ah للوحدة',
      kwhEach: 'kWh للوحدة',
      maxAcs: 'أقصى عدد مكيفات',
      maxAcBtu: 'أقصى حجم مكيف',
      maxAcBtuHelp: 'اتركه فارغًا لتجاوز فحص الحجم.',
      array: 'ألواح',
      inverterKw: 'إنفرتر',
    },
    recipe: {
      panel: 'اللوح',
      battery: 'البطارية',
      singleInverter: 'إنفرتر مفرد — حتى',
      parallelInverter: 'إنفرترات متوازية — للوحدة',
      stand: 'القاعدة',
      panelsPerStand: 'ألواح لكل قاعدة',
      perPanel: 'لكل لوح',
      perInverter: 'لكل إنفرتر',
      fixed: 'بنود ثابتة',
      part: 'القطعة',
      qty: 'الكمية',
      addLine: 'إضافة بند',
      removeLine: 'حذف البند',
      derived: 'ما يجمعه هذا',
    },
    appliances: {
      appliance: 'الجهاز',
      watts: 'الواط',
      hoursPerDay: 'ساعات في اليوم',
      night: 'يعمل ليلًا',
      alwaysOn: 'يعمل دائمًا',
      heavy: 'ثقيل',
      otherDevice: 'الافتراض لجهاز يكتبه العميل بنفسه',
      lighting: 'الإنارة',
      bulbWatts: { led: 'مصباح LED', regular: 'مصباح عادي', mixed: 'مختلط' },
      lightingHours: 'ساعات الإنارة في اليوم',
      cold: 'الثلاجة والفريزر',
      fridgeWatts: 'واط الثلاجة',
      freezerWatts: 'واط الفريزر',
      duty: 'نسبة وقت التشغيل (0–1)',
      ac: 'التكييف',
      acStandard: 'واط لكل BTU — مكيف عادي',
      acInverter: 'واط لكل BTU — مكيف إنفرتر',
      assumedAcBtu: 'الحجم المفترض عندما لا يعرفه العميل',
    },
    household: {
      sun: 'الشمس والفقد',
      peakSunHours: 'ساعات الشمس الفعّالة في اليوم',
      peakSunHoursHelp: 'ساعات أقل تعني ألواحًا أكثر لنفس الحمل.',
      systemEfficiency: 'كفاءة النظام (0–1)',
      systemEfficiencyHelp: 'الفقد في الكوابل والحرارة والغبار. قيمة أقل تعني ألواحًا أكثر.',
      battery: 'البطارية',
      dodLiquid: 'النسبة القابلة للاستخدام — سائلة (0–1)',
      dodLithium: 'النسبة القابلة للاستخدام — ليثيوم (0–1)',
      liquidVolts: 'جهد البطارية السائلة',
      nightHours: 'الساعات التي تحمل فيها البطارية حمل الليل',
      lifespan: 'عمر البطارية المعروض للعملاء (سنوات)',
      inverter: 'الإنفرتر',
      safetyFactor: 'هامش الأمان على حمل الذروة',
      safetyFactorHelp: '1.25 يجعل الإنفرتر أكبر من الذروة بنسبة 25%.',
      diversityFactor: 'معامل التنوّع (0–1)',
      diversityFactorHelp: 'لا يعمل كل شيء معًا؛ 0.8 يفترض 80% من الذروة.',
      kvaToKw: 'معامل القدرة (kW لكل kVA)',
      surge: 'مضاعِفات تيار البدء',
      surgeHelp: 'الضواغط تسحب أكثر من متوسطها عند البدء.',
      ac: 'التكييف',
      acBtuCapMode: 'عندما يكون المكيف أكبر مما تسمح به الباقة',
      acBtuCapModeOptions: {
        advisory: 'تنبيه مع عرض الباقة',
        strict: 'نقل العميل إلى الباقة الأكبر',
      },
      roof: 'السطح',
      panelArea: 'مساحة السطح لكل لوح (م²)',
      roofArea: 'المساحة القابلة للاستخدام حسب الإجابة (م²)',
      roofAreaHelp: 'الصفر يلغي الفحص لتلك الإجابة.',
    },
    commercial: {
      constants: 'الثوابت',
      batteryEfficiency: 'كفاءة البطارية (0–1)',
      systemEfficiency: 'كفاءة النظام (0–1)',
      peakSunHours: 'ساعات الشمس الفعّالة في اليوم',
      maxDcAcRatio: 'تنبيه عندما تتجاوز الألواح ÷ الإنفرتر',
      parts: 'القطع',
      panel: 'اللوح',
      battery: 'البطارية',
      stand: 'القاعدة',
      ladder: 'أحجام الإنفرتر المتوفرة',
      priced: 'مسعَّر',
      addPrice: 'إضافة سعر',
      handOver: 'تحويل الأنظمة إلى هذه الطريقة فوق (kW)',
      handOverHelp: 'طلب الإنفرتر بعد هامش الأمان. تحته تُستخدم إنفرترات منزلية متوازية.',
      quantitiesFixed: 'كميات البنود ثابتة حتى يؤكدها العميل.',
    },
    notEditable:
      'غير قابل للتعديل هنا: العملة، رقم الإصدار، تحويل BTU إلى طن، معاملات حالة الثلاجة، الأحمال المستقبلية، قائمة «المشمول» وكميات قطع الأنظمة الكبيرة.',
    heading: (n) => `${n}`,

    reviewLabel: 'مراجعة التغييرات',
    reviewChanges: {
      one: 'مراجعة تغيير واحد',
      two: 'مراجعة تغييرين',
      few: 'مراجعة {n} تغييرات',
      many: 'مراجعة {n} تغييرًا',
      other: 'مراجعة {n} تغيير',
    },
    changesCount: {
      one: 'تغيير واحد',
      two: 'تغييران',
      few: '{n} تغييرات',
      many: '{n} تغييرًا',
      other: '{n} تغيير',
    },
    problemsCount: {
      one: 'مشكلة واحدة',
      two: 'مشكلتان',
      few: '{n} مشاكل',
      many: '{n} مشكلة',
      other: '{n} مشكلة',
    },
    showProblem: 'عرض',
    fixFirst: 'عالج المشاكل قبل المراجعة.',
    noChanges: 'لا تغييرات',
    discard: 'تجاهل التغييرات',
    problemsTitle: 'مشاكل في هذه المسودة',
    review: {
      title: 'المراجعة قبل النشر',
      rollbackTitle: 'تفعيل إصدار أقدم',
      close: 'إغلاق',
      whatChanged: 'ما الذي تغيّر',
      effect: 'أثره على عروض حقيقية',
      effectBlurb: 'سبعة منازل مرجعية، مسعَّرة بما هو ساري الآن وبهذه المسودة.',
      household: 'المنزل',
      live: 'الساري الآن',
      draft: 'بعد النشر',
      noChange: 'لا تغيير',
      changedCount: (n, total) => `يتغيّر ${n} من ${total} منازل`,
      noneChange:
        'لا يتغيّر أي من المنازل المرجعية. هذا متوقع لقيمة نادرة الاستخدام، أو لتعديل عتاد لا يحرّك حدود الباقات.',
      cannotPrice: 'لا يمكن تسعيره',
      problems: 'المشاكل',
      problemsBlurb: 'النشر متوقف حتى تُعالَج.',
      publishAs: 'نشر باسم',
      publishing: 'جارٍ النشر…',
      activate: 'تفعيل',
      activating: 'جارٍ التفعيل…',
      arrow: '←',
      empty: 'فارغ',
      unsavedWarning: 'لديك تعديلات غير محفوظة. تفعيل إصدار أقدم يتجاهلها.',
      discardAndContinue: 'تجاهل تعديلاتي والمتابعة',
      invalidVersion: 'لا يمكن تفعيل هذا الإصدار: لم يعد يجتاز الفحوص الحالية. انشر مسودة مصحّحة بدلًا منه.',
      compareTo: (v) => `مقارنةً بالساري الآن، سيغيّر ${v}:`,
    },
    outcome: {
      published: (v) => `تم نشر ${v} — يسري على الزوار الجدد الآن.`,
      activated: (v) => `تم تفعيل ${v}.`,
      failed: 'لم يُحفَظ شيء — تعذّر على جدول Google حفظ الإصدار الجديد:',
      activateFailed: 'تعذّر تفعيل هذا الإصدار:',
      invalid: 'فشلت المسودة في فحص أخير ولم تُحفَظ.',
    },
    history: {
      title: 'سجل الإصدارات',
      liveNow: 'الساري الآن',
      activate: 'تفعيل…',
      loading: 'جارٍ التحميل…',
    },
    referenceCase: {
      smallFlat: 'شقة صغيرة',
      familyHomeOneAc: 'منزل عائلي بمكيف واحد',
      homeAcAndFreezer: 'منزل بمكيف وفريزر',
      homeTwoAcs: 'منزل بمكيفين',
      shop: 'محل',
      largeVilla: 'فيلا كبيرة',
      workshop: 'ورشة',
    },
    paths: {
      section: {
        configVersion: 'الإصدار',
        currency: 'العملة',
        acBtuCapMode: 'سلوك المكيف الأكبر من الباقة',
        packages: 'الباقات',
        includes: 'العناصر المشمولة',
        addOns: 'الإضافات',
        batteryLifespanYears: 'عمر البطارية (سنوات)',
        components: 'أسعار المكوّنات',
        loadDefaults: 'افتراضات الأجهزة',
        sizing: 'تحجيم المنازل',
        customBom: 'النظام المخصّص',
        commercial: 'طريقة الأنظمة الكبيرة',
      },
      field: {
        tier: 'الباقة',
        inverterKva: 'الإنفرتر (kVA)',
        panel: 'الألواح',
        count: 'العدد',
        watts: 'الواط (W)',
        battery: 'البطارية',
        chemistry: 'نوع البطارية',
        ampHours: 'السعة (Ah)',
        kwhEach: 'سعة الوحدة (kWh)',
        maxAcUnits: 'أقصى عدد مكيفات',
        maxAcBtu: 'أقصى حجم مكيف (BTU)',
        priceLyd: 'السعر (د.ل)',
        name: 'الاسم',
        liquid: 'سائلة',
        lithium: 'ليثيوم',
        acWattsPerBtu: 'واط المكيف لكل BTU',
        standard: 'عادي',
        inverter: 'إنفرتر',
        assumedAcBtu: 'حجم المكيف المفترض عند عدم المعرفة (BTU)',
        btuPerTon: 'BTU لكل طن',
        lightingWattsByType: 'واط المصباح حسب النوع (W)',
        led: 'LED',
        regular: 'عادي',
        mixed: 'مختلط',
        lightingHours: 'ساعات الإنارة في اليوم',
        fridge: 'الثلاجة',
        freezer: 'الفريزر',
        duty: 'نسبة التشغيل',
        fridgeConditionMultiplier: 'معامل حالة الثلاجة',
        new: 'جديدة',
        old: 'قديمة',
        defaultFridgeCondition: 'حالة الثلاجة الافتراضية',
        appliancesByName: 'الأجهزة',
        hours: 'ساعات في اليوم',
        night: 'يعمل ليلًا',
        alwaysOn: 'يعمل دائمًا',
        customAppliance: 'افتراض «جهاز آخر»',
        peakSunHours: 'ساعات الشمس الفعّالة (h)',
        systemEfficiency: 'كفاءة النظام',
        inverterSafetyFactor: 'معامل أمان الإنفرتر',
        diversityFactor: 'معامل التنوّع',
        liquidBatteryVoltageV: 'جهد البطارية السائلة (V)',
        kvaToKw: 'معامل القدرة (kW لكل kVA)',
        alwaysOnNightHours: 'ساعات الليل (h)',
        dodByChemistry: 'عمق التفريغ',
        surgeFactorByCategory: 'معاملات الذروة',
        ac: 'المكيفات',
        cold: 'الثلاجات والفريزرات',
        lighting: 'الإنارة',
        appliance: 'الأجهزة الأخرى',
        panelAreaM2: 'مساحة اللوح (م²)',
        roofAreaM2ByAnswer: 'مساحة السطح حسب الإجابة (م²)',
        single: 'إنفرتر مفرد',
        parallel: 'إنفرتر متوازٍ',
        maxKw: 'الأقصى (kW)',
        unitKw: 'للوحدة (kW)',
        component: 'القطعة',
        stand: 'القاعدة',
        panelsPerStand: 'ألواح لكل قاعدة',
        perPanel: 'بنود لكل لوح',
        perInverter: 'بنود لكل إنفرتر',
        fixed: 'بنود ثابتة',
        qty: 'الكمية',
        roundUpToLyd: 'التقريب لأعلى إلى (د.ل)',
        minimumLyd: 'الحد الأدنى للسعر (د.ل)',
        batteryEfficiency: 'كفاءة البطارية',
        inverterLadder: 'أحجام الإنفرتر',
        kw: 'الحجم (kW)',
        maxDcAcRatio: 'أقصى نسبة DC:AC',
        customerPath: 'عروض العملاء',
        takesOverAboveKw: 'الطريقة التجارية فوق (kW)',
      },
      packageItem: (tier) => `باقة ${tier}`,
      listItem: (n) => `البند ${n}`,
      ladderItem: (n) => `الحجم ${n}`,
      reason: {
        positive: 'يجب أن يكون رقمًا أكبر من 0',
        nonNegative: 'يجب أن يكون 0 أو أكثر',
        wholeNumber: 'يجب أن يكون عددًا صحيحًا، 0 أو أكثر',
        between: (min, max) => `يجب أن يكون بين ${min} و${max}`,
        fraction: 'يجب أن يكون أكبر من 0 ولا يتجاوز 1',
        positiveOrEmpty: 'يجب أن يكون فارغًا أو رقمًا أكبر من 0',
        monotonic: 'يجب ألا تنخفض أسعار الباقات من S إلى XXL',
        floorBelowXxl: (n) => `يجب ألا يقل عن سعر باقة XXL (${n})، وإلا صار النظام المخصّص أرخص منها`,
        unknownComponent: 'يشير إلى قطعة غير موجودة في قائمة أسعار المكوّنات',
        missingPreset: (name) => `النموذج يعرض «${name}»، فيلزمه رقم استهلاك`,
        ascending: 'يجب أن تتدرّج الأحجام من الأصغر إلى الأكبر',
        atLeastOne: 'يلزم بند واحد على الأقل',
        needsName: 'يلزم اسم قطعة',
        emptyName: 'أحد المكوّنات بلا اسم',
        addOn: 'كل إضافة تحتاج اسمًا وسعرًا أكبر من 0',
        chemistry: 'يجب أن تكون سائلة أو ليثيوم',
        acBtuCapMode: 'يجب أن يكون «تنبيه مع عرض الباقة» أو «نقل العميل إلى الباقة الأكبر»',
        newOrOld: 'يجب أن تكون جديدة أو قديمة',
        liquidBattery: 'البطارية السائلة تحتاج عددًا صحيحًا أكبر من 0 وسعة Ah أكبر من 0',
        lithiumBattery: 'بطارية الليثيوم تحتاج عددًا صحيحًا أكبر من 0 وسعة kWh أكبر من 0',
        panelSpec: 'يلزم عدد ألواح صحيح أكبر من 0 وواط أكبر من 0',
        wattsDuty: 'يلزم واط أكبر من 0 ونسبة تشغيل أكبر من 0 ولا تتجاوز 1',
        wattsHours: 'يلزم واط أكبر من 0 وساعات 0 أو أكثر',
        watts: 'يلزم واط أكبر من 0',
        hours24: 'يجب أن يكون بين 0 و24 ساعة',
        pairPositive: 'يجب أن تكون القيمتان أكبر من 0',
        allPositive: 'يجب أن تكون كل قيمة أكبر من 0',
        dodPair: 'يجب أن تكون قيمتا السائلة والليثيوم أكبر من 0 ولا تتجاوزان 1',
        lifespanPair: 'يجب أن تكون قيمتا السائلة والليثيوم أكبر من 0',
        surge: 'يجب أن يكون كل معامل ذروة بين 1 و10',
        panelArea: 'يجب أن تكون أكبر من 0 وأقل من 20 م²',
        roofAreas: 'يجب أن تكون كل مساحة سطح 0 م² أو أكثر',
        componentAndWatts: 'يلزم قطعة من قائمة الأسعار وواط أكبر من 0',
        componentAndKwh: 'يلزم قطعة من قائمة الأسعار وسعة kWh أكبر من 0',
        inverterParts: 'يحتاج الإنفرتران قطعة من قائمة الأسعار وقدرة kW أكبر من 0',
        standParts: 'يلزم قطعة من قائمة الأسعار وعدد صحيح من الألواح لكل قاعدة أكبر من 0',
        qty: 'يلزم كمية أكبر من 0',
        kwAndName: 'يلزم حجم kW أكبر من 0 واسم قطعة',
        ratio: 'يجب أن يكون 1 على الأقل',
        structural: 'هذا الجزء من الإعدادات ليس بالشكل المتوقع — أعد تحميل الصفحة قبل التعديل',
      },
    },
  },

  sizing: {
    banner:
      'تقدير داخلي — ليس عرض سعر للعميل. محسوب بطريقة القمة للمشاريع التجارية؛ الأسعار تقريبية وكل رقم يحتاج اعتماد مهندس.',
    job: 'المشروع',
    batteryKwh: 'طاقة البطاريات اليومية (kWh)',
    dayLoadKw: 'حمل النهار (kW)',
    peakKw: 'حمل الذروة (kW)',
    help: 'طاقة البطاريات هي ما يجب سحبه منها ليلًا. حمل النهار هو ما تغذّيه الألواح مباشرة. الذروة تساوي حمل النهار إن لم تُحدَّد.',
    usingPeak: 'المستخدم',
    checkNumbers: 'راجع الأرقام',
    system: 'النظام',
    batteries: 'بطاريات',
    arrayCaption: 'ألواح',
    inverter: 'إنفرتر',
    steps: {
      gross: 'الطاقة الإجمالية، ثم عدد البطاريات',
      recharge: 'لإعادة شحن البطاريات',
      array: 'قدرة الألواح، ثم عددها',
      inverter: 'الإنفرتر من حمل الذروة',
    },
    loadPlusCharging: 'الحمل + الشحن يحتاج',
    checkBeforeQuoting: 'راجع قبل التسعير',
    partsList: 'قائمة القطع التقريبية',
    cols: { item: 'القطعة', qty: 'العدد', unit: 'سعر الوحدة', total: 'الإجمالي' },
    noPrice: 'بدون سعر',
    pricedRounded: 'القطع المسعّرة، مقرّبة لأعلى',
    unpricedNote: {
      one: 'قطعة واحدة ليست في قائمة الأسعار، لذا الإجمالي أعلاه غير كامل:',
      two: 'قطعتان ليستا في قائمة الأسعار، لذا الإجمالي أعلاه غير كامل:',
      few: '{n} قطع ليست في قائمة الأسعار، لذا الإجمالي أعلاه غير كامل:',
      many: '{n} قطعة ليست في قائمة الأسعار، لذا الإجمالي أعلاه غير كامل:',
      other: '{n} قطعة ليست في قائمة الأسعار، لذا الإجمالي أعلاه غير كامل:',
    },
    unpricedHint: 'أضفها في الأسعار ← أسعار المكوّنات — تجدها مثبّتة في الأعلى — وسيكتمل الإجمالي.',
    method: 'الطريقة',
    methodParts: {
      batteryEff: 'كفاءة البطارية',
      systemEff: 'كفاءة النظام',
      sunHours: 'ساعات شمس فعّالة',
      panels: 'واط للوح',
      batteries: 'kWh للبطارية',
    },
    builtInFigures: 'هذه هي الأرقام المضمّنة — انشر إعدادات الأسعار مرة واحدة لتصبح قابلة للتعديل.',
    builtInPrices: 'أسعار المكوّنات من القائمة المضمّنة.',
    customerLive: 'عروض العملاء: الأنظمة التي يتجاوز طلب الإنفرتر فيها',
    customerLiveTail: 'تُسعَّر بهذه الطريقة تلقائيًا.',
    customerWaiting: 'ستتحول عروض العملاء إلى هذه الطريقة للأنظمة فوق',
    customerWaitingTail: 'فور تسعير هذه المكوّنات في قائمة الأسعار:',
    customerMeanwhile: 'حتى ذلك الحين تُسعَّر الأنظمة الكبيرة من قائمة المكوّنات المنزلية — تلقائيًا أيضًا، وبرقم دائمًا.',
    summary: {
      title: 'تحجيم تقريبي — ليس عرض سعر للعميل',
      batteries: 'البطاريات',
      panels: 'الألواح',
      inverter: 'الإنفرتر',
      gross: 'إجمالي',
      array: 'ألواح',
      partsTotal: 'إجمالي القطع التقريبي',
      stillUnpriced: {
        one: 'قطعة واحدة بلا سعر',
        two: 'قطعتان بلا سعر',
        few: '{n} قطع بلا سعر',
        many: '{n} قطعة بلا سعر',
        other: '{n} قطعة بلا سعر',
      },
    },
  },
}

export const ADMIN_BUNDLES: Record<Lang, AdminStrings> = { en: EN, ar: AR }
